/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class CreatePrescriptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePrescriptionPanel
     */
    public CreatePrescriptionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        patientInfoPanel = new javax.swing.JPanel();
        patientSearchLabel = new javax.swing.JLabel();
        patientSearchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        selectedPatientLabel = new javax.swing.JLabel();
        patientNameLabel = new javax.swing.JLabel();
        patientDetailsLabel = new javax.swing.JLabel();
        prescriptionFormPanel = new javax.swing.JPanel();
        medicationLabel = new javax.swing.JLabel();
        medicationTextField = new javax.swing.JTextField();
        dosageLabel = new javax.swing.JLabel();
        dosageTextField = new javax.swing.JTextField();
        strengthLabel = new javax.swing.JLabel();
        strengthTextField = new javax.swing.JTextField();
        frequencyLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        durationTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        refillsLabel = new javax.swing.JLabel();
        refillsComboBox = new javax.swing.JComboBox<>();
        instructionsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionsTextArea = new javax.swing.JTextArea();
        pharmacyLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setText("Create Prescription");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 6, -1, -1));

        descriptionLabel.setText("Create electronic prescription for patient ");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        patientInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Information"));
        patientInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientSearchLabel.setText("Search Patient ");
        patientInfoPanel.add(patientSearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        patientInfoPanel.add(patientSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        searchButton.setText("Search Button");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        patientInfoPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        selectedPatientLabel.setText("Selected Pateint");
        patientInfoPanel.add(selectedPatientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        patientNameLabel.setText("[No patient selected]");
        patientInfoPanel.add(patientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        patientDetailsLabel.setText("-");
        patientInfoPanel.add(patientDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 94, 19, -1));

        add(patientInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 740, 110));

        prescriptionFormPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Prescription Details")));
        prescriptionFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicationLabel.setText("Medication Name");
        prescriptionFormPanel.add(medicationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        medicationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicationTextFieldActionPerformed(evt);
            }
        });
        prescriptionFormPanel.add(medicationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, -1));

        dosageLabel.setText("Dosage");
        prescriptionFormPanel.add(dosageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        dosageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageTextFieldActionPerformed(evt);
            }
        });
        prescriptionFormPanel.add(dosageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        strengthLabel.setText("Strength");
        prescriptionFormPanel.add(strengthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        prescriptionFormPanel.add(strengthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        frequencyLabel.setText("Frequency");
        prescriptionFormPanel.add(frequencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        durationLabel.setText("Duration");
        prescriptionFormPanel.add(durationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        durationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextFieldActionPerformed(evt);
            }
        });
        prescriptionFormPanel.add(durationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Once daily", "Twice daily", "3 times daily", "4 times daily", "As needed" }));
        prescriptionFormPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        quantityLabel.setText("Quantity");
        prescriptionFormPanel.add(quantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });
        prescriptionFormPanel.add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        refillsLabel.setText("Refills Allowed");
        prescriptionFormPanel.add(refillsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        refillsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        prescriptionFormPanel.add(refillsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        instructionsLabel.setText("Instructions for Patient");
        prescriptionFormPanel.add(instructionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        instructionsTextArea.setColumns(20);
        instructionsTextArea.setRows(5);
        jScrollPane1.setViewportView(instructionsTextArea);

        prescriptionFormPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 710, 50));

        add(prescriptionFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 740, 350));

        pharmacyLabel.setText("Preferred Pharmacy");
        add(pharmacyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Pharmacy", "CVS Pharmacy", "Walgreens", "Rite Aid" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        clearButton.setText("Clear");
        add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        submitButton.setText("Submit Prescription");
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void medicationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicationTextFieldActionPerformed

    private void dosageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosageTextFieldActionPerformed

    private void durationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel dosageLabel;
    private javax.swing.JTextField dosageTextField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JTextArea instructionsTextArea;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel medicationLabel;
    private javax.swing.JTextField medicationTextField;
    private javax.swing.JLabel patientDetailsLabel;
    private javax.swing.JPanel patientInfoPanel;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel patientSearchLabel;
    private javax.swing.JTextField patientSearchTextField;
    private javax.swing.JLabel pharmacyLabel;
    private javax.swing.JPanel prescriptionFormPanel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JComboBox<String> refillsComboBox;
    private javax.swing.JLabel refillsLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel selectedPatientLabel;
    private javax.swing.JLabel strengthLabel;
    private javax.swing.JTextField strengthTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
