/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class HealthcareProviderDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthcareProviderDashboardPanel
     */
    public HealthcareProviderDashboardPanel() {
        initComponents();
        setSize(1150,720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        patientsCard = new javax.swing.JPanel();
        patientsCountLabel = new javax.swing.JLabel();
        patientsTextLabel = new javax.swing.JLabel();
        prescriptionsCard = new javax.swing.JPanel();
        prescriptionsCountLabel = new javax.swing.JLabel();
        prescriptionsTextLabel = new javax.swing.JLabel();
        verifiedCard = new javax.swing.JPanel();
        verifiedCountLabel = new javax.swing.JLabel();
        verifiedTextLabel = new javax.swing.JLabel();
        pendingCard = new javax.swing.JPanel();
        pendingCountLabel = new javax.swing.JLabel();
        pendingTextLabel = new javax.swing.JLabel();
        quickActionsLabel = new javax.swing.JLabel();
        checkInPatientButton = new javax.swing.JButton();
        createPrescriptionButton = new javax.swing.JButton();
        verifyInsuranceButton = new javax.swing.JButton();
        viewRecordsButton = new javax.swing.JButton();
        appointmentsSectionLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        appointmentsScrollPane = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1150, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("HEALTHCARE PROVIDER DASHBOARD");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 700, 35));

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionLabel.setText("Manage patient care and prescriptions");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 700, 20));

        welcomeLabel.setText("Welcome, Dr. [Name]");
        add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, 700, 20));

        logoutButton.setText("Logout");
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 100, 36));

        patientsCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        patientsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientsCountLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        patientsCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientsCountLabel.setText("15");
        patientsCard.add(patientsCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        patientsTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        patientsTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientsTextLabel.setText("Patients Today");
        patientsCard.add(patientsTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        add(patientsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 120));

        prescriptionsCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        prescriptionsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prescriptionsCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        prescriptionsCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prescriptionsCountLabel.setText("8");
        prescriptionsCard.add(prescriptionsCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        prescriptionsTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prescriptionsTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prescriptionsTextLabel.setText("Prescriptions Pending");
        prescriptionsCard.add(prescriptionsTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        add(prescriptionsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 250, 120));

        verifiedCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        verifiedCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verifiedCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        verifiedCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifiedCountLabel.setText("12");
        verifiedCard.add(verifiedCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        verifiedTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verifiedTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifiedTextLabel.setText("Verified Insurance");
        verifiedCard.add(verifiedTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        add(verifiedCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 250, 120));

        pendingCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pendingCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pendingCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingCountLabel.setText("5");
        pendingCard.add(pendingCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        pendingTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pendingTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingTextLabel.setText("Pending Claims");
        pendingCard.add(pendingTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        add(pendingCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 250, 120));

        quickActionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        quickActionsLabel.setText("QUICK ACTIONS");
        add(quickActionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, 300, 25));

        checkInPatientButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInPatientButton.setText("Check In Patient");
        add(checkInPatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 36));

        createPrescriptionButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createPrescriptionButton.setText("Create Prescription");
        add(createPrescriptionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 180, 36));

        verifyInsuranceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        verifyInsuranceButton.setText("Verify Insurance");
        add(verifyInsuranceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 180, 36));

        viewRecordsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewRecordsButton.setText("View Records");
        add(viewRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 180, 36));

        appointmentsSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        appointmentsSectionLabel.setText("TODAY'S APPOINTMENTS");
        add(appointmentsSectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 400, 25));

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("Refresh");
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 100, 30));

        appointmentsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        appointmentsTable.setRowHeight(35);
        appointmentsScrollPane.setViewportView(appointmentsTable);

        add(appointmentsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 1070, 280));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane appointmentsScrollPane;
    private javax.swing.JLabel appointmentsSectionLabel;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JButton checkInPatientButton;
    private javax.swing.JButton createPrescriptionButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel patientsCard;
    private javax.swing.JLabel patientsCountLabel;
    private javax.swing.JLabel patientsTextLabel;
    private javax.swing.JPanel pendingCard;
    private javax.swing.JLabel pendingCountLabel;
    private javax.swing.JLabel pendingTextLabel;
    private javax.swing.JPanel prescriptionsCard;
    private javax.swing.JLabel prescriptionsCountLabel;
    private javax.swing.JLabel prescriptionsTextLabel;
    private javax.swing.JLabel quickActionsLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel verifiedCard;
    private javax.swing.JLabel verifiedCountLabel;
    private javax.swing.JLabel verifiedTextLabel;
    private javax.swing.JButton verifyInsuranceButton;
    private javax.swing.JButton viewRecordsButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
