/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class HealthcareProviderDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthcareProviderDashboardPanel
     */
    public HealthcareProviderDashboardPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        patientsCard = new javax.swing.JPanel();
        patientsCountLabel = new javax.swing.JLabel();
        patientsTextLabel = new javax.swing.JLabel();
        prescriptionsCard = new javax.swing.JPanel();
        prescriptionsCountLabel = new javax.swing.JLabel();
        prescriptionsTextLabel = new javax.swing.JLabel();
        verifiedCard = new javax.swing.JPanel();
        verifiedTextLabel = new javax.swing.JLabel();
        verifiedCountLabel = new javax.swing.JLabel();
        pendingCard = new javax.swing.JPanel();
        pendingCountLabel = new javax.swing.JLabel();
        pendingTextLabel = new javax.swing.JLabel();
        quickActionsLabel = new javax.swing.JLabel();
        checkInPatientButton = new javax.swing.JButton();
        createPrescriptionButton = new javax.swing.JButton();
        verifyInsuranceButton = new javax.swing.JButton();
        viewRecordsButton = new javax.swing.JButton();
        appointmentsSectionLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        appointmentsScrollPane = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1150, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("HEALTHCARE PROVIDER DASHBOARD");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 28));

        descriptionLabel.setText("Manage patient care and prescriptions");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 16));

        welcomeLabel.setText("Welcome, Dr. [Name]");
        add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 16));

        logoutButton.setText("Logout");
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 30));

        patientsCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        patientsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientsCountLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        patientsCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientsCountLabel.setText("15");
        patientsCard.add(patientsCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 145, 32));

        patientsTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        patientsTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientsTextLabel.setText("Patients Today");
        patientsCard.add(patientsTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        add(patientsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 175, 95));

        prescriptionsCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        prescriptionsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prescriptionsCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        prescriptionsCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prescriptionsCountLabel.setText("8");
        prescriptionsCard.add(prescriptionsCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 145, 32));

        prescriptionsTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prescriptionsTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prescriptionsTextLabel.setText("Prescriptions Pending");
        prescriptionsCard.add(prescriptionsTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        add(prescriptionsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 175, 95));

        verifiedCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        verifiedCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verifiedTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verifiedTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifiedTextLabel.setText("Verified Insurance");
        verifiedCard.add(verifiedTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        verifiedCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        verifiedCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifiedCountLabel.setText("12");
        verifiedCard.add(verifiedCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 145, 32));

        add(verifiedCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 175, 95));

        pendingCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pendingCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pendingCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingCountLabel.setText("5");
        pendingCard.add(pendingCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 145, 32));

        pendingTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pendingTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingTextLabel.setText("Pending Claims");
        pendingCard.add(pendingTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        add(pendingCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 175, 95));

        quickActionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        quickActionsLabel.setText("QUICK ACTIONS");
        add(quickActionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 20));

        checkInPatientButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInPatientButton.setText("Check In Patient");
        checkInPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInPatientButtonActionPerformed(evt);
            }
        });
        add(checkInPatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 36));

        createPrescriptionButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createPrescriptionButton.setText("Create Prescription");
        createPrescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPrescriptionButtonActionPerformed(evt);
            }
        });
        add(createPrescriptionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, 36));

        verifyInsuranceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        verifyInsuranceButton.setText("Verify Insurance");
        verifyInsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyInsuranceButtonActionPerformed(evt);
            }
        });
        add(verifyInsuranceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 170, 36));

        viewRecordsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewRecordsButton.setText("View Records");
        add(viewRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 170, 36));

        appointmentsSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        appointmentsSectionLabel.setText("TODAY'S APPOINTMENTS");
        add(appointmentsSectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 300, 20));

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 90, 26));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        appointmentsScrollPane.setViewportView(jTable2);

        add(appointmentsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 745, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void createPrescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPrescriptionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPrescriptionButtonActionPerformed

    private void checkInPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInPatientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInPatientButtonActionPerformed

    private void verifyInsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyInsuranceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verifyInsuranceButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane appointmentsScrollPane;
    private javax.swing.JLabel appointmentsSectionLabel;
    private javax.swing.JButton checkInPatientButton;
    private javax.swing.JButton createPrescriptionButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel patientsCard;
    private javax.swing.JLabel patientsCountLabel;
    private javax.swing.JLabel patientsTextLabel;
    private javax.swing.JPanel pendingCard;
    private javax.swing.JLabel pendingCountLabel;
    private javax.swing.JLabel pendingTextLabel;
    private javax.swing.JPanel prescriptionsCard;
    private javax.swing.JLabel prescriptionsCountLabel;
    private javax.swing.JLabel prescriptionsTextLabel;
    private javax.swing.JLabel quickActionsLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel verifiedCard;
    private javax.swing.JLabel verifiedCountLabel;
    private javax.swing.JLabel verifiedTextLabel;
    private javax.swing.JButton verifyInsuranceButton;
    private javax.swing.JButton viewRecordsButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
