/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBoxPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        loginBoxPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginBoxPanelLayout = new javax.swing.GroupLayout(loginBoxPanel);
        loginBoxPanel.setLayout(loginBoxPanelLayout);
        loginBoxPanelLayout.setHorizontalGroup(
            loginBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBoxPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(loginBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton)
                    .addGroup(loginBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(usernameTextField)
                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        loginBoxPanelLayout.setVerticalGroup(
            loginBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBoxPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(loginButton)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(loginBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(loginBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Get entered credentials
        String username = usernameTextField.getText().trim();
        String password = new String(passwordField.getPassword());
        
        // Validate input
        if (username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter both username and password!",
                "Login Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get SystemData instance
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Authenticate using UserDirectory
        model.User authenticatedUser = systemData.getUserDirectory().authenticate(username, password);
        
        if (authenticatedUser != null) {
            // Set current user in SystemData
            systemData.setCurrentUser(authenticatedUser);
            
            // Get reference to MainApplicationFrame
            java.awt.Container parent = this.getParent();
            while (parent != null && !(parent instanceof MainApplicationFrame)) {
                parent = parent.getParent();
            }
            
            if (parent instanceof MainApplicationFrame) {
                MainApplicationFrame mainFrame = (MainApplicationFrame) parent;
                
                // Navigate based on role
                if (authenticatedUser.getRole().isAdminRole()) {
                    // System Admin or other admin roles
                    SystemAdminDashboardPanel adminDashboard = new SystemAdminDashboardPanel();
                    mainFrame.addPanel(adminDashboard, "systemAdminDashboard");
                    mainFrame.showPanel("systemAdminDashboard");
                    
                } else if (authenticatedUser.getRole().isPatient()) {
                // Patient role

                // Initialize sample data for this patient (IMPORTANT!)
                String patientId = authenticatedUser.getPerson().getPersonId();
                systemData.initializeSampleDataForPatient(patientId);

                PatientDashboardPanel patientDashboard = new PatientDashboardPanel();
                mainFrame.addPanel(patientDashboard, "patientDashboard");
                mainFrame.showPanel("patientDashboard");
                    
                } else if (authenticatedUser.getRole() == model.Role.CLAIMS_PROCESSOR) {
                    // Claims Processor role
                    ClaimsProcessorDashboard claimsDashboard = new ClaimsProcessorDashboard();
                    mainFrame.addPanel(claimsDashboard, "claimsProcessorDashboard");
                    mainFrame.showPanel("claimsProcessorDashboard");
                    
                } else if (authenticatedUser.getRole() == model.Role.CLAIMS_PROCESSOR) {
                    // Claims Processor role
                    ClaimsProcessorDashboard claimsDashboard = new ClaimsProcessorDashboard();
                    mainFrame.addPanel(claimsDashboard, "claimsProcessorDashboard");
                    mainFrame.showPanel("claimsProcessorDashboard");
                    
                } else if (authenticatedUser.getRole() == model.Role.CLAIMS_PROCESSOR) {
                    // Claims Processor role
                    ClaimsProcessorDashboard claimsDashboard = new ClaimsProcessorDashboard();
                    mainFrame.addPanel(claimsDashboard, "claimsProcessorDashboard");
                    mainFrame.showPanel("claimsProcessorDashboard");
                    
                } else {
                    // Other roles (Doctor, Pharmacist, etc.)
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Dashboard for role '" + authenticatedUser.getRole().getDisplayName() + "' is under development.",
                        "Coming Soon",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                
                // Clear fields after successful login
                usernameTextField.setText("");
                passwordField.setText("");
            }
            
        } else {
            // Authentication failed
            javax.swing.JOptionPane.showMessageDialog(this,
                "Invalid username or password!\n\n" +
                "Test Credentials:\n" +
                "System Admin - Username: admin, Password: admin123\n" +
                "Patient - Username: patient, Password: patient123",
                "Login Failed",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel loginBoxPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
