/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class MainApplicationFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainApplicationFrame
     */
    public MainApplicationFrame() {
        initComponents();
        setLocationRelativeTo(null);

        // Try to load saved data
        loadSavedData();

        // Add LoginPanel
        LoginPanel loginPanel = new LoginPanel();
        mainContainerPanel.add(loginPanel, "loginPanel");
        showPanel("loginPanel");

        // Add window closing listener to save data
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                saveDataOnExit();
            }
        });
    }

    /**
     * Load saved data on startup
     */
    private void loadSavedData() {
        if (business.SystemData.hasSavedData()) {
            int response = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Found saved data from previous session.\n\n" +
                            "Do you want to load it?\n\n" +
                            "Click 'No' to start with fresh sample data.",
                    "Load Saved Data?",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (response == javax.swing.JOptionPane.YES_OPTION) {
                business.SystemData loadedData = business.SystemData.loadFromFile();
                if (loadedData != null) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Data loaded successfully!\n\n" +
                                    "File size: " + utils.FileHandler.getFormattedFileSize(),
                            "Data Loaded",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Failed to load saved data.\n\nStarting with fresh data.",
                            "Load Failed",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }

    /**
     * Save data on application exit
     */
    private void saveDataOnExit() {
        business.SystemData systemData = business.SystemData.getInstance();

        int response = javax.swing.JOptionPane.showConfirmDialog(this,
                "Do you want to save all data before exiting?",
                "Save Data?",
                javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (response == javax.swing.JOptionPane.CANCEL_OPTION) {
            // Cancel exit
            return;
        }

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            boolean saved = systemData.saveToFile();
            if (saved) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Data saved successfully!\n\n" +
                                "File: healthguard360_data.dat\n" +
                                "Size: " + utils.FileHandler.getFormattedFileSize(),
                        "Data Saved",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Failed to save data!",
                        "Save Failed",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

        // Exit application
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainContainerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("HealthGuard360");

        mainContainerPanel.setLayout(new java.awt.CardLayout());

        // Use BorderLayout instead of GroupLayout to prevent layout shifting
        getContentPane().setLayout(new java.awt.BorderLayout());

        // Create a header panel for the title
        javax.swing.JPanel headerPanel = new javax.swing.JPanel();
        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        headerPanel.add(jLabel1);

        // Add components to content pane
        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
        getContentPane().add(mainContainerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApplicationFrame().setVisible(true);
            }
        });
    }

    /**
     * Method to switch between different panels/screens
     * 
     * @param panelName The name of the panel to display
     */
    public void showPanel(String panelName) {
        java.awt.CardLayout layout = (java.awt.CardLayout) mainContainerPanel.getLayout();
        layout.show(mainContainerPanel, panelName);
    }

    /**
     * Method to add a new panel to the container
     * 
     * @param panel     The panel to add
     * @param panelName The unique name identifier for this panel
     */
    public void addPanel(javax.swing.JPanel panel, String panelName) {
        mainContainerPanel.add(panel, panelName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainContainerPanel;
    // End of variables declaration//GEN-END:variables
}
