/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class ManageEnterprisesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterprisesPanel
     */
    public ManageEnterprisesPanel() {
        initComponents();
        loadEnterprises();
    }
    
    /**
     * Load all enterprises from EnterpriseDirectory into table
     */
    private void loadEnterprises() {
        // Get SystemData instance
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Get all enterprises
        java.util.List<model.Enterprise> enterpriseList = systemData.getEnterpriseDirectory().getAllEnterprises();
        
        // Get table model
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) enterprisesTable.getModel();
        
        // Clear existing rows
        tableModel.setRowCount(0);
        
        // Add each enterprise to table
        for (model.Enterprise enterprise : enterpriseList) {
            tableModel.addRow(new Object[]{
                enterprise.getEnterpriseId(),
                enterprise.getEnterpriseName(),
                enterprise.getEnterpriseType().getDisplayName(),
                enterprise.getFormattedCreatedDate()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createEnterprisePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enterpriseNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enterpriseTypeComboBox = new javax.swing.JComboBox<>();
        createEnterpriseButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisesTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1150, 720));

        createEnterprisePanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Enterprise Name:");

        jLabel2.setText("Enterprise Type");

        enterpriseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital", "Insurance Provider", "Pharmacy Chain", "Pharmaceutical Supplier" }));

        createEnterpriseButton.setText("Create Enterprise");
        createEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        enterprisesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise ID", "Enterprise Name", "Type", "Created"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterprisesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createEnterprisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(createEnterpriseButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterpriseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(clearButton)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enterpriseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEnterpriseButton)
                    .addComponent(clearButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createEnterprisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButtonActionPerformed
        // TODO add your handling code here:
        // Get input values
        String enterpriseName = enterpriseNameTextField.getText().trim();
        String selectedType = (String) enterpriseTypeComboBox.getSelectedItem();
        
        // Validate input
        if (enterpriseName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter an enterprise name!",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedType == null || selectedType.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select an enterprise type!",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Check if enterprise name already exists
        if (systemData.getEnterpriseDirectory().isEnterpriseNameExists(enterpriseName)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "An enterprise with the name '" + enterpriseName + "' already exists!",
                "Duplicate Name",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Convert selected type string to EnterpriseType enum
        model.Enterprise.EnterpriseType enterpriseType = null;
        
        switch (selectedType) {
            case "Hospital":
                enterpriseType = model.Enterprise.EnterpriseType.HOSPITAL;
                break;
            case "Insurance Provider":
                enterpriseType = model.Enterprise.EnterpriseType.INSURANCE_PROVIDER;
                break;
            case "Pharmacy Chain":
                enterpriseType = model.Enterprise.EnterpriseType.PHARMACY_CHAIN;
                break;
            case "Pharmaceutical Supplier":
                enterpriseType = model.Enterprise.EnterpriseType.PHARMACEUTICAL_SUPPLIER;
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Invalid enterprise type selected!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        // Create the enterprise using SystemData
        model.Enterprise newEnterprise = systemData.createEnterprise(enterpriseName, enterpriseType);
        
        // Reload the table to show the new enterprise
        loadEnterprises();
        
        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this,
            "Enterprise '" + enterpriseName + "' created successfully!\n" +
            "Enterprise ID: " + newEnterprise.getEnterpriseId(),
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Clear the form
        enterpriseNameTextField.setText("");
        enterpriseTypeComboBox.setSelectedIndex(0);
        enterpriseNameTextField.requestFocus();
    }//GEN-LAST:event_createEnterpriseButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        enterpriseNameTextField.setText("");
        enterpriseTypeComboBox.setSelectedIndex(0);
        enterpriseNameTextField.requestFocus();
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton createEnterpriseButton;
    private javax.swing.JPanel createEnterprisePanel;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JComboBox<String> enterpriseTypeComboBox;
    private javax.swing.JTable enterprisesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
