/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class ManageMedicationCatalogPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMedicationCatalogPanel
     */
    public ManageMedicationCatalogPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addNewButton = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox<>();
        catalogScrollPane = new javax.swing.JScrollPane();
        catalogTable = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        totalItemsLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Medication Catalog Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel2.setText("Add, edit, and manage medication inventory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 6, -1, -1));

        searchLabel.setText("Search:");
        add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 57, 120, -1));

        searchButton.setText("Search");
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 57, -1, -1));

        addNewButton.setText("+ Add New");
        add(addNewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 57, -1, -1));

        filterLabel.setText("Filter:");
        add(filterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, -1, -1));

        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Medications", "In Stock", "Low Stock", "Out of Stock", "Prescription", "OTC " }));
        add(filterComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 120, -1));

        catalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Med ID", "Name", "Category", "Stock", "Price", "Exp Date", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catalogTable.setRowHeight(30);
        catalogScrollPane.setViewportView(catalogTable);

        add(catalogScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, 740, 360));

        editButton.setText("Edit Selected");
        add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        deleteButton.setText("Delete Selected");
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        exportButton.setText("Export Catalog");
        add(exportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        totalItemsLabel.setText("Total Items: 125 | In Stock: 112 | Low Stock: 8 | Out of Stock: 5");
        add(totalItemsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane catalogScrollPane;
    private javax.swing.JTable catalogTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel totalItemsLabel;
    // End of variables declaration//GEN-END:variables
}
