/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class ManageOrganizationsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationsPanel
     */
    public ManageOrganizationsPanel() {
        initComponents();
        loadEnterprises();
        loadOrganizations();
    }
    
    /**
     * Load enterprises into dropdown from SystemData
     */
    private void loadEnterprises() {
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Clear existing items
        enterpriseComboBox.removeAllItems();
        
        // Add default option
        enterpriseComboBox.addItem("-- Select Enterprise --");
        
        // Get all enterprises and add to dropdown
        java.util.List<model.Enterprise> enterpriseList = systemData.getEnterpriseDirectory().getAllEnterprises();
        
        for (model.Enterprise enterprise : enterpriseList) {
            enterpriseComboBox.addItem(enterprise.getEnterpriseName());
        }
    }
    
    /**
     * Load all organizations from OrganizationDirectory into table
     */
    private void loadOrganizations() {
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Get all organizations
        java.util.List<model.Organization> organizationList = systemData.getOrganizationDirectory().getAllOrganizations();
        
        // Get table model
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) organizationsTable.getModel();
        
        // Clear existing rows
        tableModel.setRowCount(0);
        
        // Add each organization to table
        for (model.Organization organization : organizationList) {
            // Find enterprise name
            model.Enterprise enterprise = systemData.getEnterpriseDirectory().findEnterpriseById(organization.getEnterpriseId());
            String enterpriseName = (enterprise != null) ? enterprise.getEnterpriseName() : "Unknown";
            
            tableModel.addRow(new Object[]{
                organization.getOrganizationId(),
                organization.getOrganizationName(),
                organization.getOrganizationType().getDisplayName(),
                enterpriseName,
                organization.getFormattedCreatedDate()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createOrganizationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        organizationNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        organizationTypeComboBox = new javax.swing.JComboBox<>();
        createOrganizationButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        organizationsTable = new javax.swing.JTable();

        createOrganizationPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Create New Organisation");

        jLabel2.setText("Select Enterprise :");

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City General Hospital", "BlueCross", "Mass Health" }));

        jLabel3.setText("Organisation Name");

        jLabel4.setText("Organisation Type");

        organizationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department", "Division", "Branch", "Unit" }));

        createOrganizationButton.setText("Create Organisation");
        createOrganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrganizationButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Existing Organisation");

        organizationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Org. ID", "Name", "Type", "Enterprise", "Created"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(organizationsTable);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createOrganizationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createOrganizationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(organizationNameTextField)
                                    .addComponent(organizationTypeComboBox, 0, 186, Short.MAX_VALUE)
                                    .addComponent(clearButton))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(createOrganizationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(organizationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(organizationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createOrganizationButton)
                    .addComponent(clearButton))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createOrganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrganizationButtonActionPerformed
        // TODO add your handling code here:
        // Get input values
        String selectedEnterpriseName = (String) enterpriseComboBox.getSelectedItem();
        String organizationName = organizationNameTextField.getText().trim();
        String selectedOrgType = (String) organizationTypeComboBox.getSelectedItem();
        
        // Validate enterprise selection
        if (selectedEnterpriseName == null || selectedEnterpriseName.equals("-- Select Enterprise --")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select an enterprise!",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate organization name
        if (organizationName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter an organization name!",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Find the selected enterprise
        model.Enterprise selectedEnterprise = systemData.getEnterpriseDirectory().findEnterpriseByName(selectedEnterpriseName);
        
        if (selectedEnterprise == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selected enterprise not found!",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if organization name already exists in this enterprise
        if (systemData.getOrganizationDirectory().isOrganizationNameExistsInEnterprise(organizationName, selectedEnterprise.getEnterpriseId())) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "An organization with the name '" + organizationName + "' already exists in " + selectedEnterpriseName + "!",
                "Duplicate Name",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Convert org type string to enum
        model.Organization.OrganizationType orgType = null;
        
        switch (selectedOrgType) {
            case "Department":
                orgType = model.Organization.OrganizationType.DEPARTMENT;
                break;
            case "Division":
                orgType = model.Organization.OrganizationType.DIVISION;
                break;
            case "Branch":
                orgType = model.Organization.OrganizationType.BRANCH;
                break;
            case "Unit":
                orgType = model.Organization.OrganizationType.UNIT;
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Invalid organization type!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        // Create the organization using SystemData (this also links it to the enterprise)
        model.Organization newOrganization = systemData.createOrganization(organizationName, orgType, selectedEnterprise.getEnterpriseId());
        
        // Reload the table
        loadOrganizations();
        
        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this,
            "Organization '" + organizationName + "' created successfully under " + selectedEnterpriseName + "!\n" +
            "Organization ID: " + newOrganization.getOrganizationId(),
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Clear the form
        enterpriseComboBox.setSelectedIndex(0);
        organizationNameTextField.setText("");
        organizationTypeComboBox.setSelectedIndex(0);
        organizationNameTextField.requestFocus();
    }//GEN-LAST:event_createOrganizationButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        // Clear all fields
        enterpriseComboBox.setSelectedIndex(0);
        organizationNameTextField.setText("");
        organizationTypeComboBox.setSelectedIndex(0);
        organizationNameTextField.requestFocus();
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton createOrganizationButton;
    private javax.swing.JPanel createOrganizationPanel;
    private javax.swing.JComboBox<String> enterpriseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField organizationNameTextField;
    private javax.swing.JComboBox<String> organizationTypeComboBox;
    private javax.swing.JTable organizationsTable;
    // End of variables declaration//GEN-END:variables
}
