/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class MyClaimsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyClaimsPanel
     */
    public MyClaimsPanel() {
        initComponents();

        // Add ActionListener to filter combo box
        statusFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadClaims();
            }
        });

        // Add ActionListener to refresh button
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadClaims();
                updateStatistics();
            }
        });

        loadClaims();
        updateStatistics();
    }

    /**
     * Load real claims for current patient from ClaimDirectory
     */
    private void loadClaims() {
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();

        // Get all claims for current patient
        java.util.List<model.Claim> patientClaims = systemData.getCurrentPatientClaims();

        // Get selected filter
        String selectedFilter = (String) statusFilterComboBox.getSelectedItem();

        // Get table model
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) claimsTable.getModel();

        // Clear existing rows
        tableModel.setRowCount(0);

        // Add each claim to table (with filtering)
        for (model.Claim claim : patientClaims) {
            // Apply filter
            if (selectedFilter != null && !selectedFilter.equals("All Claims")) {
                String claimStatus = claim.getClaimStatus().getDisplayName();
                if (!claimStatus.equals(selectedFilter)) {
                    continue; // Skip claims that don't match the filter
                }
            }

            tableModel.addRow(new Object[] {
                    claim.getClaimNumber(),
                    claim.getPolicyNumber(),
                    claim.getFormattedServiceDate(),
                    claim.getProviderName(),
                    claim.getFormattedClaimAmount(),
                    claim.getClaimStatus().getDisplayName(),
                    claim.getFormattedSubmittedDate(),
                    claim.getFormattedLastUpdatedDate()
            });
        }
    }

    /**
     * Update statistics labels with real data
     */
    private void updateStatistics() {
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();

        // Get real counts
        int totalClaims = systemData.getClaimDirectory().getClaimCountForPatient(systemData.getCurrentPatientId());
        int pendingClaims = systemData.getCurrentPatientPendingClaimCount();
        int approvedClaims = systemData.getCurrentPatientApprovedClaimCount();
        int deniedClaims = systemData.getCurrentPatientDeniedClaimCount();

        // Update labels
        totalClaimsLabel.setText("Total: " + totalClaims);
        pendingClaimsStatsLabel.setText("Pending: " + pendingClaims);
        approvedClaimsStatsLabel.setText("Approved: " + approvedClaims);
        deniedClaimsStatsLabel.setText("Denied: " + deniedClaims);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryStatsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalClaimsLabel = new javax.swing.JLabel();
        pendingClaimsStatsLabel = new javax.swing.JLabel();
        approvedClaimsStatsLabel = new javax.swing.JLabel();
        deniedClaimsStatsLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        statusFilterComboBox = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        claimsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        claimNumberValueLabel = new javax.swing.JLabel();
        policyNumberValueLabel = new javax.swing.JLabel();
        diagnosisValueLabel = new javax.swing.JLabel();
        serviceTypeValueLabel = new javax.swing.JLabel();
        amountValueLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        statusValueLabel = new javax.swing.JLabel();
        submittedDateValueLabel = new javax.swing.JLabel();
        lastUpdatedValueLabel = new javax.swing.JLabel();
        viewDocumentsButton = new javax.swing.JButton();
        withdrawClaimButton = new javax.swing.JButton();

        summaryStatsPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("My Insurance Claims");

        totalClaimsLabel.setText("Total: 5");

        pendingClaimsStatsLabel.setText("Pending: 2");

        approvedClaimsStatsLabel.setText("Approved: 2");

        deniedClaimsStatsLabel.setText("Denied: 1");

        jLabel6.setText("Filter By Status:");

        statusFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "All Claims", "Approved", "Under Review", "Paid", "Denied", "Submitted", " ", " " }));

        refreshButton.setText("Refresh");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        claimsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null }
                },
                new String[] {
                        "Claim #", "Policy", "Service", "Provider", "Amount", "Status", "Submit", "Update"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        claimsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claimsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(claimsTable);

        jLabel7.setText("Claim Details:");

        jLabel8.setText("Claim Number:");

        jLabel9.setText("Policy Number:");

        jLabel10.setText("Diagnosis:");

        jLabel11.setText("Service Type:");

        jLabel12.setText("Claim Amount:");

        claimNumberValueLabel.setText("Select a claim to view details");

        policyNumberValueLabel.setText("--");

        diagnosisValueLabel.setText("--");

        serviceTypeValueLabel.setText("--");

        amountValueLabel.setText("--");

        jLabel19.setText("Status:");

        jLabel20.setText("Submitted Date:");

        jLabel21.setText("Last Updated:");

        statusValueLabel.setText("--");

        submittedDateValueLabel.setText("--");

        lastUpdatedValueLabel.setText("--");

        viewDocumentsButton.setText("View Documents");
        viewDocumentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDocumentsButtonActionPerformed(evt);
            }
        });

        withdrawClaimButton.setText("Withdraw Claim");
        withdrawClaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawClaimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(summaryStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(265, 265, 265))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(totalClaimsLabel))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(69, 69, 69)
                                                                .addComponent(pendingClaimsStatsLabel)
                                                                .addGap(56, 56, 56)
                                                                .addComponent(approvedClaimsStatsLabel)
                                                                .addGap(78, 78, 78)
                                                                .addComponent(deniedClaimsStatsLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(statusFilterComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(refreshButton))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 588,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(claimNumberValueLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(policyNumberValueLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(diagnosisValueLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel11)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(serviceTypeValueLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel12)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(amountValueLabel)))
                                                                .addGap(204, 204, 204)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel20)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(submittedDateValueLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel19)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(statusValueLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel21)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lastUpdatedValueLabel))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(84, 84, 84)
                                                                .addComponent(viewDocumentsButton)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(withdrawClaimButton)))))
                                .addContainerGap(92, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(summaryStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalClaimsLabel)
                                        .addComponent(pendingClaimsStatsLabel)
                                        .addComponent(approvedClaimsStatsLabel)
                                        .addComponent(deniedClaimsStatsLabel))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(statusFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(refreshButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(claimNumberValueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(policyNumberValueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(diagnosisValueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(serviceTypeValueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(amountValueLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel19)
                                                        .addComponent(statusValueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel20)
                                                        .addComponent(submittedDateValueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel21)
                                                        .addComponent(lastUpdatedValueLabel))))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewDocumentsButton)
                                        .addComponent(withdrawClaimButton))
                                .addContainerGap(14, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDocumentsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viewDocumentsButtonActionPerformed
        // TODO add your handling code here:
        if (claimNumberValueLabel.getText().equals("Select a claim to view details")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a claim from the table first!",
                    "No Claim Selected",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Opening supporting documents for claim: " + claimNumberValueLabel.getText() +
                            "\n\nDocuments:\n- Hospital Bill.pdf\n- Doctor's Notes.pdf\n- Lab Results.pdf" +
                            "\n\n(Document viewer will be implemented later)",
                    "Claim Documents",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_viewDocumentsButtonActionPerformed

    private void withdrawClaimButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_withdrawClaimButtonActionPerformed
        // TODO add your handling code here:
        if (claimNumberValueLabel.getText().equals("Select a claim to view details")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a claim from the table first!",
                    "No Claim Selected",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String claimNumber = claimNumberValueLabel.getText();

        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();
        model.Claim claim = systemData.getClaimDirectory().findClaimByNumber(claimNumber);

        if (claim == null) {
            return;
        }

        // Check if can be withdrawn
        if (!claim.canBeWithdrawn()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cannot withdraw a claim with status: " + claim.getClaimStatus().getDisplayName() +
                            "\n\nOnly 'Submitted' or 'Under Review' claims can be withdrawn.",
                    "Cannot Withdraw",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm withdrawal
        int response = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to withdraw claim " + claimNumber + "?\n\n" +
                        "This action cannot be undone.",
                "Withdraw Claim",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            // Withdraw using SystemData
            boolean success = systemData.withdrawClaim(claimNumber);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Claim " + claimNumber + " has been withdrawn successfully.",
                        "Claim Withdrawn",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Reload table and stats
                loadClaims();
                updateStatistics();

                // Clear details
                claimNumberValueLabel.setText("Select a claim to view details");
                policyNumberValueLabel.setText("--");
                diagnosisValueLabel.setText("--");
                serviceTypeValueLabel.setText("--");
                amountValueLabel.setText("--");
                statusValueLabel.setText("--");
                submittedDateValueLabel.setText("--");
                lastUpdatedValueLabel.setText("--");
            }
        }
    }// GEN-LAST:event_withdrawClaimButtonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jScrollPane1MouseClicked

    private void claimsTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_claimsTableMouseClicked
        // TODO add your handling code here:
        // Get selected row
        int selectedRow = claimsTable.getSelectedRow();

        if (selectedRow >= 0) {
            // Get claim number from selected row
            String claimNumber = claimsTable.getValueAt(selectedRow, 0).toString();

            // Get SystemData
            business.SystemData systemData = business.SystemData.getInstance();

            // Find the claim
            model.Claim selectedClaim = systemData.getClaimDirectory().findClaimByNumber(claimNumber);

            if (selectedClaim != null) {
                // Update all detail labels with real data
                claimNumberValueLabel.setText(selectedClaim.getClaimNumber());
                policyNumberValueLabel.setText(selectedClaim.getPolicyNumber());
                diagnosisValueLabel.setText(selectedClaim.getDiagnosis());
                serviceTypeValueLabel.setText(selectedClaim.getServiceType().getDisplayName());
                amountValueLabel.setText(selectedClaim.getFormattedClaimAmount());
                statusValueLabel.setText(selectedClaim.getClaimStatus().getDisplayName());
                submittedDateValueLabel.setText(selectedClaim.getFormattedSubmittedDate());
                lastUpdatedValueLabel.setText(selectedClaim.getFormattedLastUpdatedDate());

                // Color code status
                model.Claim.ClaimStatus status = selectedClaim.getClaimStatus();
                if (status == model.Claim.ClaimStatus.APPROVED || status == model.Claim.ClaimStatus.PAID) {
                    statusValueLabel.setForeground(new java.awt.Color(40, 167, 69)); // Green
                } else if (status == model.Claim.ClaimStatus.DENIED) {
                    statusValueLabel.setForeground(new java.awt.Color(220, 53, 69)); // Red
                } else if (status == model.Claim.ClaimStatus.UNDER_REVIEW) {
                    statusValueLabel.setForeground(new java.awt.Color(255, 152, 0)); // Orange
                } else {
                    statusValueLabel.setForeground(new java.awt.Color(33, 150, 243)); // Blue
                }
            }
        }
    }// GEN-LAST:event_claimsTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountValueLabel;
    private javax.swing.JLabel approvedClaimsStatsLabel;
    private javax.swing.JLabel claimNumberValueLabel;
    private javax.swing.JTable claimsTable;
    private javax.swing.JLabel deniedClaimsStatsLabel;
    private javax.swing.JLabel diagnosisValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastUpdatedValueLabel;
    private javax.swing.JLabel pendingClaimsStatsLabel;
    private javax.swing.JLabel policyNumberValueLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel serviceTypeValueLabel;
    private javax.swing.JComboBox<String> statusFilterComboBox;
    private javax.swing.JLabel statusValueLabel;
    private javax.swing.JLabel submittedDateValueLabel;
    private javax.swing.JPanel summaryStatsPanel;
    private javax.swing.JLabel totalClaimsLabel;
    private javax.swing.JButton viewDocumentsButton;
    private javax.swing.JButton withdrawClaimButton;
    // End of variables declaration//GEN-END:variables
}
