/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class MyPoliciesPanel extends javax.swing.JPanel {

        /**
         * Creates new form MyPoliciesPanel
         */
        public MyPoliciesPanel() {
                initComponents();

                // Add ActionListener to filter combo box
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loadPolicies();
                        }
                });

                loadPolicies();
        }

        /**
         * Load real policies for current patient from PolicyDirectory
         */
        private void loadPolicies() {
                System.out.println("=== loadPolicies() called ===");

                // Get SystemData
                business.SystemData systemData = business.SystemData.getInstance();
                System.out.println("SystemData instance: " + systemData);

                // Get all policies for current patient
                java.util.List<model.Policy> patientPolicies = systemData.getCurrentPatientPolicies();
                System.out.println("Number of policies found: " + patientPolicies.size());

                // Get selected filter
                String selectedFilter = (String) jComboBox1.getSelectedItem();
                System.out.println("Selected filter: " + selectedFilter);

                // Get table model
                javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) jTable1
                                .getModel();
                System.out.println("Table model: " + tableModel);
                System.out.println("Table column count: " + tableModel.getColumnCount());

                // Clear existing rows
                tableModel.setRowCount(0);
                System.out.println("Table cleared");

                // Add each policy to table (with filtering)
                for (model.Policy policy : patientPolicies) {
                        // Apply filter
                        if (selectedFilter != null && !selectedFilter.equals("All Policies")) {
                                if (selectedFilter.equals("Active") && !policy.isCurrentlyActive()) {
                                        continue; // Skip non-active policies
                                }
                                if (selectedFilter.equals("Expired") && !policy.isExpired()) {
                                        continue; // Skip non-expired policies
                                }
                        }

                        System.out.println("Adding policy: " + policy.getPolicyNumber());

                        tableModel.addRow(new Object[] {
                                        policy.getPolicyNumber(),
                                        policy.getPolicyType().getDisplayName(),
                                        policy.getFormattedCoverageAmount(),
                                        policy.getFormattedMonthlyPremium(),
                                        policy.getPolicyStatus().getDisplayName(),
                                        policy.getFormattedStartDate(),
                                        policy.getFormattedExpiryDate()
                        });
                }

                System.out.println("Final row count in table: " + tableModel.getRowCount());
                System.out.println("=== loadPolicies() complete ===");
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                policyNumberValueLabel = new javax.swing.JLabel();
                policyTypeValueLabel = new javax.swing.JLabel();
                coverageAmountValueLabel = new javax.swing.JLabel();
                deductibleValueLabel = new javax.swing.JLabel();
                copaymentValueLabel = new javax.swing.JLabel();
                premiumValueLabel = new javax.swing.JLabel();
                startDateValueLabel = new javax.swing.JLabel();
                expiryDateValueLabel = new javax.swing.JLabel();
                beneficiariesValueLabel = new javax.swing.JLabel();
                statusValueLabel = new javax.swing.JLabel();
                viewPolicyDocButton = new javax.swing.JButton();
                renewPolicyButton = new javax.swing.JButton();
                cancelPolicyButton = new javax.swing.JButton();

                jPanel1.setLayout(new java.awt.BorderLayout());

                jLabel1.setText("Filter By Status");

                jComboBox1
                                .setModel(new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "All Policies", "Active", "Expired" }));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "Policy #", "Type", "Coverage", "Premium", "Status", "Start", "Expiry"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTable1MouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(jTable1);

                jLabel2.setText("Policy Details");

                jLabel3.setText("Policy Type:");

                jLabel4.setText("Coverage Amount:");

                jLabel5.setText("Deductible:");

                jLabel6.setText("Co-payment: ");

                jLabel7.setText("Monthly Premium:");

                jLabel8.setText("Start Date:");

                jLabel10.setText("Status:");

                jLabel11.setText("Expiry Date:");

                jLabel12.setText("Beneficiaries:");

                policyNumberValueLabel.setText("Select a policy to view details");

                viewPolicyDocButton.setText("View Policy Document");
                viewPolicyDocButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                viewPolicyDocButtonActionPerformed(evt);
                        }
                });

                renewPolicyButton.setText("Renew Policy");
                renewPolicyButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                renewPolicyButtonActionPerformed(evt);
                        }
                });

                cancelPolicyButton.setText("Cancel Policy");
                cancelPolicyButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelPolicyButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                653,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jPanel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(242, 242, 242))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jComboBox1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel4)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(coverageAmountValueLabel))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel6)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(copaymentValueLabel))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel8)
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(startDateValueLabel))
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(premiumValueLabel)))
                                                                                                                                .addGap(230, 230,
                                                                                                                                                230)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel12)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(beneficiariesValueLabel))
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel11)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(expiryDateValueLabel))
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel10)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                .addComponent(statusValueLabel))))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel5)
                                                                                                                                .addGap(28, 28, 28)
                                                                                                                                .addComponent(deductibleValueLabel))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(viewPolicyDocButton)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(renewPolicyButton))
                                                                                                                                                .addGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                .addGroup(layout
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                .addComponent(jLabel2)
                                                                                                                                                                                                .addComponent(jLabel3))
                                                                                                                                                                                .addGap(27, 27, 27)
                                                                                                                                                                                .addGroup(layout
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                policyTypeValueLabel)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                policyNumberValueLabel))))
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(cancelPolicyButton)))
                                                                                                .addGap(0, 496, Short.MAX_VALUE)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(83, 83, 83)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(46, 46, 46)
                                                                                                .addComponent(jPanel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                199,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(30, 30, 30)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(policyNumberValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(policyTypeValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(coverageAmountValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(deductibleValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(copaymentValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(premiumValueLabel)
                                                                                .addComponent(statusValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(startDateValueLabel)
                                                                                .addComponent(expiryDateValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(beneficiariesValueLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(viewPolicyDocButton)
                                                                                .addComponent(renewPolicyButton)
                                                                                .addComponent(cancelPolicyButton))
                                                                .addContainerGap(12, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void viewPolicyDocButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viewPolicyDocButtonActionPerformed
                // Check if a policy is selected
                if (policyNumberValueLabel.getText().equals("Select a policy to view details")) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Please select a policy from the table first!",
                                        "No Policy Selected",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                }

                try {
                        // Get the selected policy
                        String policyNumber = policyNumberValueLabel.getText();
                        business.SystemData systemData = business.SystemData.getInstance();
                        model.Policy selectedPolicy = systemData.getPolicyDirectory().findPolicyByNumber(policyNumber);

                        if (selectedPolicy == null) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Error: Could not find policy details.",
                                                "Policy Not Found",
                                                javax.swing.JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // Generate PDF
                        String pdfPath = utils.PolicyPDFGenerator.generatePolicyDocument(selectedPolicy);

                        // Open the PDF with default system viewer
                        java.io.File pdfFile = new java.io.File(pdfPath);
                        if (pdfFile.exists()) {
                                if (java.awt.Desktop.isDesktopSupported()) {
                                        java.awt.Desktop.getDesktop().open(pdfFile);

                                        javax.swing.JOptionPane.showMessageDialog(this,
                                                        "Policy document generated successfully!\n\n" +
                                                                        "Location: " + pdfPath,
                                                        "PDF Generated",
                                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                        javax.swing.JOptionPane.showMessageDialog(this,
                                                        "PDF generated but cannot open automatically.\n\n" +
                                                                        "Location: " + pdfPath + "\n\n" +
                                                                        "Please open the file manually.",
                                                        "PDF Generated",
                                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                }
                        } else {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Error: PDF file was not created successfully.",
                                                "File Not Found",
                                                javax.swing.JOptionPane.ERROR_MESSAGE);
                        }

                } catch (java.io.IOException ex) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Error generating PDF document:\n" + ex.getMessage() +
                                                        "\n\nPlease ensure you have write permissions to your Documents folder.",
                                        "PDF Generation Error",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        ex.printStackTrace();
                } catch (Exception ex) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Unexpected error:\n" + ex.getMessage(),
                                        "Error",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        ex.printStackTrace();
                }
        }// GEN-LAST:event_viewPolicyDocButtonActionPerformed

        private void renewPolicyButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // Step 1: Validate - Check if a policy is selected
                if (policyNumberValueLabel.getText().equals("Select a policy to view details")) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Please select a policy from the table first!",
                                        "No Policy Selected",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                }

                try {
                        // Get the selected policy
                        String policyNumber = policyNumberValueLabel.getText();
                        business.SystemData systemData = business.SystemData.getInstance();
                        model.Policy selectedPolicy = systemData.getPolicyDirectory().findPolicyByNumber(policyNumber);

                        if (selectedPolicy == null) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Error: Could not find policy details.",
                                                "Policy Not Found",
                                                javax.swing.JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // Validate policy status - can only renew ACTIVE or EXPIRED policies
                        if (!selectedPolicy.canBeRenewed()) {
                                String statusMsg = selectedPolicy.getPolicyStatus().getDisplayName();
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Cannot renew this policy.\n\n" +
                                                                "Current Status: " + statusMsg + "\n\n" +
                                                                "Only ACTIVE or EXPIRED policies can be renewed.\n" +
                                                                "CANCELLED and SUSPENDED policies cannot be renewed.",
                                                "Renewal Not Allowed",
                                                javax.swing.JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // Step 2: Duration Selection - Ask user for renewal duration
                        String[] options = { "1 Year", "2 Years", "3 Years" };
                        String selectedDuration = (String) javax.swing.JOptionPane.showInputDialog(
                                        this,
                                        "Select renewal duration for policy:\n" + policyNumber,
                                        "Renew Policy - Select Duration",
                                        javax.swing.JOptionPane.QUESTION_MESSAGE,
                                        null,
                                        options,
                                        options[0]);

                        // User cancelled
                        if (selectedDuration == null) {
                                return;
                        }

                        // Parse duration
                        int years = Integer.parseInt(selectedDuration.split(" ")[0]);

                        // Step 3: Calculate new terms
                        double currentPremium = selectedPolicy.getMonthlyPremium();
                        double newPremium = currentPremium * 1.07; // 7% increase
                        double newAnnualPremium = newPremium * 12;

                        java.time.LocalDate newStartDate = selectedPolicy.getExpiryDate().plusDays(1);
                        java.time.LocalDate newExpiryDate = newStartDate.plusYears(years);
                        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter
                                        .ofPattern("MM/dd/yyyy");

                        // Step 4: Confirmation - Show detailed confirmation dialog
                        String confirmationMessage = String.format(
                                        "POLICY RENEWAL CONFIRMATION\n\n" +
                                                        "Policy Number: %s\n" +
                                                        "Policy Type: %s\n\n" +
                                                        "── Current Terms ──\n" +
                                                        "Monthly Premium: %s\n" +
                                                        "Expiry Date: %s\n\n" +
                                                        "── New Terms (After Renewal) ──\n" +
                                                        "Duration: %d Year%s\n" +
                                                        "New Monthly Premium: $%.2f (+7%%)\n" +
                                                        "New Annual Premium: $%.2f\n" +
                                                        "New Start Date: %s\n" +
                                                        "New Expiry Date: %s\n\n" +
                                                        "Do you want to proceed with this renewal?",
                                        selectedPolicy.getPolicyNumber(),
                                        selectedPolicy.getPolicyType().getDisplayName(),
                                        selectedPolicy.getFormattedMonthlyPremium(),
                                        selectedPolicy.getFormattedExpiryDate(),
                                        years,
                                        (years > 1 ? "s" : ""),
                                        newPremium,
                                        newAnnualPremium,
                                        newStartDate.format(formatter),
                                        newExpiryDate.format(formatter));

                        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                                        this,
                                        confirmationMessage,
                                        "Confirm Policy Renewal",
                                        javax.swing.JOptionPane.YES_NO_OPTION,
                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                        // User cancelled
                        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                                return;
                        }

                        // Step 5: Execute renewal
                        selectedPolicy.renewPolicy(years);

                        // Save changes to PolicyDirectory
                        systemData.getPolicyDirectory().updatePolicy(selectedPolicy);

                        // Step 6: Success notification and UI refresh
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Policy renewed successfully!\n\n" +
                                                        "Policy Number: " + selectedPolicy.getPolicyNumber() + "\n" +
                                                        "New Expiry Date: " + selectedPolicy.getFormattedExpiryDate()
                                                        + "\n" +
                                                        "New Monthly Premium: "
                                                        + selectedPolicy.getFormattedMonthlyPremium(),
                                        "Renewal Successful",
                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                        // Refresh the policies table and details
                        loadPolicies();

                        // Update the detail panel with new information
                        policyNumberValueLabel.setText(selectedPolicy.getPolicyNumber());
                        policyTypeValueLabel.setText(selectedPolicy.getPolicyType().getDisplayName());
                        coverageAmountValueLabel.setText(selectedPolicy.getFormattedCoverageAmount());
                        deductibleValueLabel.setText(selectedPolicy.getFormattedDeductible());
                        copaymentValueLabel.setText(selectedPolicy.getFormattedCopayment());
                        premiumValueLabel.setText(selectedPolicy.getFormattedMonthlyPremium());
                        startDateValueLabel.setText(selectedPolicy.getFormattedStartDate());
                        expiryDateValueLabel.setText(selectedPolicy.getFormattedExpiryDate());
                        statusValueLabel.setText(selectedPolicy.getPolicyStatus().getDisplayName());
                        beneficiariesValueLabel.setText(selectedPolicy.getBeneficiariesString());

                        // Update status color
                        if (selectedPolicy.isCurrentlyActive()) {
                                statusValueLabel.setForeground(new java.awt.Color(40, 167, 69)); // Green
                        }

                } catch (Exception ex) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Error renewing policy:\n" + ex.getMessage(),
                                        "Renewal Error",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        ex.printStackTrace();
                }
        }

        private void cancelPolicyButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // Step 1: Validate - Check if a policy is selected
                if (policyNumberValueLabel.getText().equals("Select a policy to view details")) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Please select a policy from the table first!",
                                        "No Policy Selected",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                }

                try {
                        // Get the selected policy
                        String policyNumber = policyNumberValueLabel.getText();
                        business.SystemData systemData = business.SystemData.getInstance();
                        model.Policy selectedPolicy = systemData.getPolicyDirectory().findPolicyByNumber(policyNumber);

                        if (selectedPolicy == null) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Error: Could not find policy details.",
                                                "Policy Not Found",
                                                javax.swing.JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // Step 2: Validate policy status - cannot cancel already cancelled policies
                        if (selectedPolicy.getPolicyStatus() == model.Policy.PolicyStatus.CANCELLED) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "This policy is already cancelled.\n\n" +
                                                                "Policy Number: " + selectedPolicy.getPolicyNumber()
                                                                + "\n" +
                                                                "Status: Cancelled",
                                                "Already Cancelled",
                                                javax.swing.JOptionPane.WARNING_MESSAGE);
                                return;
                        }

                        // Step 3: Warning Confirmation - Show serious warning dialog
                        String warningMessage = String.format(
                                        "⚠️  POLICY CANCELLATION WARNING  ⚠️\n\n" +
                                                        "You are about to CANCEL the following policy:\n\n" +
                                                        "Policy Number: %s\n" +
                                                        "Policy Type: %s\n" +
                                                        "Coverage Amount: %s\n" +
                                                        "Current Status: %s\n\n" +
                                                        "IMPORTANT:\n" +
                                                        "• This action CANNOT be undone\n" +
                                                        "• Your coverage will be terminated\n" +
                                                        "• You will lose all benefits\n" +
                                                        "• Cancelled policies CANNOT be renewed\n\n" +
                                                        "Are you absolutely sure you want to cancel this policy?",
                                        selectedPolicy.getPolicyNumber(),
                                        selectedPolicy.getPolicyType().getDisplayName(),
                                        selectedPolicy.getFormattedCoverageAmount(),
                                        selectedPolicy.getPolicyStatus().getDisplayName());

                        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                                        this,
                                        warningMessage,
                                        "Confirm Policy Cancellation",
                                        javax.swing.JOptionPane.YES_NO_OPTION,
                                        javax.swing.JOptionPane.WARNING_MESSAGE);

                        // User cancelled
                        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                                return;
                        }

                        // Step 4: Execute cancellation
                        selectedPolicy.cancelPolicy();

                        // Save changes to PolicyDirectory
                        systemData.getPolicyDirectory().updatePolicy(selectedPolicy);

                        // Step 5: Success notification and UI refresh
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Policy has been cancelled.\n\n" +
                                                        "Policy Number: " + selectedPolicy.getPolicyNumber() + "\n" +
                                                        "Status: " + selectedPolicy.getPolicyStatus().getDisplayName()
                                                        + "\n\n" +
                                                        "This policy is no longer active and cannot be renewed.",
                                        "Policy Cancelled",
                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                        // Refresh the policies table and details
                        loadPolicies();

                        // Update the detail panel with new information
                        policyNumberValueLabel.setText(selectedPolicy.getPolicyNumber());
                        policyTypeValueLabel.setText(selectedPolicy.getPolicyType().getDisplayName());
                        coverageAmountValueLabel.setText(selectedPolicy.getFormattedCoverageAmount());
                        deductibleValueLabel.setText(selectedPolicy.getFormattedDeductible());
                        copaymentValueLabel.setText(selectedPolicy.getFormattedCopayment());
                        premiumValueLabel.setText(selectedPolicy.getFormattedMonthlyPremium());
                        startDateValueLabel.setText(selectedPolicy.getFormattedStartDate());
                        expiryDateValueLabel.setText(selectedPolicy.getFormattedExpiryDate());
                        statusValueLabel.setText(selectedPolicy.getPolicyStatus().getDisplayName());
                        beneficiariesValueLabel.setText(selectedPolicy.getBeneficiariesString());

                        // Update status color to gray for cancelled
                        statusValueLabel.setForeground(new java.awt.Color(150, 150, 150)); // Gray

                } catch (Exception ex) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Error cancelling policy:\n" + ex.getMessage(),
                                        "Cancellation Error",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        ex.printStackTrace();
                }
        }

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
                // TODO add your handling code here:
                // Get selected row
                int selectedRow = jTable1.getSelectedRow();

                if (selectedRow >= 0) {
                        // Get policy number from selected row
                        String policyNumber = jTable1.getValueAt(selectedRow, 0).toString();

                        // Get SystemData
                        business.SystemData systemData = business.SystemData.getInstance();

                        // Find the policy
                        model.Policy selectedPolicy = systemData.getPolicyDirectory().findPolicyByNumber(policyNumber);

                        if (selectedPolicy != null) {
                                // Update all detail labels with real data
                                policyNumberValueLabel.setText(selectedPolicy.getPolicyNumber());
                                policyTypeValueLabel.setText(selectedPolicy.getPolicyType().getDisplayName());
                                coverageAmountValueLabel.setText(selectedPolicy.getFormattedCoverageAmount());
                                deductibleValueLabel.setText(selectedPolicy.getFormattedDeductible());
                                copaymentValueLabel.setText(selectedPolicy.getFormattedCopayment());
                                premiumValueLabel.setText(selectedPolicy.getFormattedMonthlyPremium());
                                startDateValueLabel.setText(selectedPolicy.getFormattedStartDate());
                                expiryDateValueLabel.setText(selectedPolicy.getFormattedExpiryDate());
                                statusValueLabel.setText(selectedPolicy.getPolicyStatus().getDisplayName());
                                beneficiariesValueLabel.setText(selectedPolicy.getBeneficiariesString());

                                // Color code status
                                if (selectedPolicy.isCurrentlyActive()) {
                                        statusValueLabel.setForeground(new java.awt.Color(40, 167, 69)); // Green
                                } else if (selectedPolicy.isExpired()) {
                                        statusValueLabel.setForeground(new java.awt.Color(220, 53, 69)); // Red
                                } else {
                                        statusValueLabel.setForeground(new java.awt.Color(100, 100, 100)); // Gray
                                }
                        }
                }
        }// GEN-LAST:event_jTable1MouseClicked

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel beneficiariesValueLabel;
        private javax.swing.JButton cancelPolicyButton;
        private javax.swing.JLabel copaymentValueLabel;
        private javax.swing.JLabel coverageAmountValueLabel;
        private javax.swing.JLabel deductibleValueLabel;
        private javax.swing.JLabel expiryDateValueLabel;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel policyNumberValueLabel;
        private javax.swing.JLabel policyTypeValueLabel;
        private javax.swing.JLabel premiumValueLabel;
        private javax.swing.JButton renewPolicyButton;
        private javax.swing.JLabel startDateValueLabel;
        private javax.swing.JLabel statusValueLabel;
        private javax.swing.JButton viewPolicyDocButton;
        // End of variables declaration//GEN-END:variables
}
