/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class MyPoliciesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyPoliciesPanel
     */
    public MyPoliciesPanel() {
        initComponents();
        loadPolicies();
    }
    
    /**
     * Load real policies for current patient from PolicyDirectory
     */
    private void loadPolicies() {
        System.out.println("=== loadPolicies() called ===");
        
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();
        System.out.println("SystemData instance: " + systemData);
        
        // Get all policies for current patient
        java.util.List<model.Policy> patientPolicies = systemData.getCurrentPatientPolicies();
        System.out.println("Number of policies found: " + patientPolicies.size());
        
        // Get table model
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        System.out.println("Table model: " + tableModel);
        System.out.println("Table column count: " + tableModel.getColumnCount());
        
        // Clear existing rows
        tableModel.setRowCount(0);
        System.out.println("Table cleared");
        
        // Add each policy to table
        for (model.Policy policy : patientPolicies) {
            System.out.println("Adding policy: " + policy.getPolicyNumber());
            
            tableModel.addRow(new Object[]{
                policy.getPolicyNumber(),
                policy.getPolicyType().getDisplayName(),
                policy.getFormattedCoverageAmount(),
                policy.getFormattedMonthlyPremium(),
                policy.getPolicyStatus().getDisplayName(),
                policy.getFormattedStartDate(),
                policy.getFormattedExpiryDate()
            });
        }
        
        System.out.println("Final row count in table: " + tableModel.getRowCount());
        System.out.println("=== loadPolicies() complete ===");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        policyNumberValueLabel = new javax.swing.JLabel();
        policyTypeValueLabel = new javax.swing.JLabel();
        coverageAmountValueLabel = new javax.swing.JLabel();
        deductibleValueLabel = new javax.swing.JLabel();
        copaymentValueLabel = new javax.swing.JLabel();
        premiumValueLabel = new javax.swing.JLabel();
        startDateValueLabel = new javax.swing.JLabel();
        expiryDateValueLabel = new javax.swing.JLabel();
        beneficiariesValueLabel = new javax.swing.JLabel();
        statusValueLabel = new javax.swing.JLabel();
        viewPolicyDocButton = new javax.swing.JButton();
        renewPolicyButton = new javax.swing.JButton();
        cancelPolicyButton = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Filter By Status");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Policies", "Active", "Expired" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Policy #", "Type", "Coverage", "Premium", "Status", "Start", "Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Policy Details");

        jLabel3.setText("Policy Type:");

        jLabel4.setText("Coverage Amount:");

        jLabel5.setText("Deductible:");

        jLabel6.setText("Co-payment: ");

        jLabel7.setText("Monthly Premium:");

        jLabel8.setText("Start Date:");

        jLabel10.setText("Status:");

        jLabel11.setText("Expiry Date:");

        jLabel12.setText("Beneficiaries:");

        policyNumberValueLabel.setText("Select a policy to view details");

        viewPolicyDocButton.setText("View Policy Document");
        viewPolicyDocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPolicyDocButtonActionPerformed(evt);
            }
        });

        renewPolicyButton.setText("Renew Policy");

        cancelPolicyButton.setText("Cancel Policy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(coverageAmountValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(copaymentValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(startDateValueLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(premiumValueLabel)))
                                .addGap(230, 230, 230)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(beneficiariesValueLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(expiryDateValueLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(statusValueLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(deductibleValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(viewPolicyDocButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(renewPolicyButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(policyTypeValueLabel)
                                            .addComponent(policyNumberValueLabel))))
                                .addGap(18, 18, 18)
                                .addComponent(cancelPolicyButton)))
                        .addGap(0, 496, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(policyNumberValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(policyTypeValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(coverageAmountValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deductibleValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(copaymentValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(premiumValueLabel)
                    .addComponent(statusValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(startDateValueLabel)
                    .addComponent(expiryDateValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(beneficiariesValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPolicyDocButton)
                    .addComponent(renewPolicyButton)
                    .addComponent(cancelPolicyButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewPolicyDocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPolicyDocButtonActionPerformed
        // TODO add your handling code here:
        if (policyNumberValueLabel.getText().equals("Select a policy to view details")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a policy from the table first!",
                "No Policy Selected",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Opening policy document for: " + policyNumberValueLabel.getText() +
                "\n\nPolicy Type: " + policyTypeValueLabel.getText() +
                "\nCoverage: " + coverageAmountValueLabel.getText() +
                "\n\n(PDF viewer functionality will be added later)",
                "Policy Document",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_viewPolicyDocButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // Get selected row
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow >= 0) {
            // Get policy number from selected row
            String policyNumber = jTable1.getValueAt(selectedRow, 0).toString();
            
            // Get SystemData
            business.SystemData systemData = business.SystemData.getInstance();
            
            // Find the policy
            model.Policy selectedPolicy = systemData.getPolicyDirectory().findPolicyByNumber(policyNumber);
            
            if (selectedPolicy != null) {
                // Update all detail labels with real data
                policyNumberValueLabel.setText(selectedPolicy.getPolicyNumber());
                policyTypeValueLabel.setText(selectedPolicy.getPolicyType().getDisplayName());
                coverageAmountValueLabel.setText(selectedPolicy.getFormattedCoverageAmount());
                deductibleValueLabel.setText(selectedPolicy.getFormattedDeductible());
                copaymentValueLabel.setText(selectedPolicy.getFormattedCopayment());
                premiumValueLabel.setText(selectedPolicy.getFormattedMonthlyPremium());
                startDateValueLabel.setText(selectedPolicy.getFormattedStartDate());
                expiryDateValueLabel.setText(selectedPolicy.getFormattedExpiryDate());
                statusValueLabel.setText(selectedPolicy.getPolicyStatus().getDisplayName());
                beneficiariesValueLabel.setText(selectedPolicy.getBeneficiariesString());
                
                // Color code status
                if (selectedPolicy.isCurrentlyActive()) {
                    statusValueLabel.setForeground(new java.awt.Color(40, 167, 69)); // Green
                } else if (selectedPolicy.isExpired()) {
                    statusValueLabel.setForeground(new java.awt.Color(220, 53, 69)); // Red
                } else {
                    statusValueLabel.setForeground(new java.awt.Color(100, 100, 100)); // Gray
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beneficiariesValueLabel;
    private javax.swing.JButton cancelPolicyButton;
    private javax.swing.JLabel copaymentValueLabel;
    private javax.swing.JLabel coverageAmountValueLabel;
    private javax.swing.JLabel deductibleValueLabel;
    private javax.swing.JLabel expiryDateValueLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel policyNumberValueLabel;
    private javax.swing.JLabel policyTypeValueLabel;
    private javax.swing.JLabel premiumValueLabel;
    private javax.swing.JButton renewPolicyButton;
    private javax.swing.JLabel startDateValueLabel;
    private javax.swing.JLabel statusValueLabel;
    private javax.swing.JButton viewPolicyDocButton;
    // End of variables declaration//GEN-END:variables
}
