/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class MyPrescriptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyPrescriptionsPanel
     */
    public MyPrescriptionsPanel() {
        initComponents();
        loadPrescriptions();
        updateStatistics();
    }
    
    /**
     * Load real prescriptions for current patient
     */
    private void loadPrescriptions() {
        business.SystemData systemData = business.SystemData.getInstance();
        java.util.List<model.Prescription> patientRx = systemData.getCurrentPatientPrescriptions();
        
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) prescriptionsTable.getModel();
        tableModel.setRowCount(0);
        
        for (model.Prescription rx : patientRx) {
            tableModel.addRow(new Object[]{
                rx.getPrescriptionNumber(),
                "Medication Name", // Will be linked to Medication object later
                rx.getDosage(),
                rx.getQuantity() + " units",
                rx.getRefillsRemaining(),
                rx.getFormattedPrescribedDate(),
                "Pharmacy Name", // Will be linked to Pharmacy later
                rx.getStatus().getDisplayName()
            });
        }
    }
    
    /**
     * Update statistics
     */
    private void updateStatistics() {
        business.SystemData systemData = business.SystemData.getInstance();
        
        int active = systemData.getCurrentPatientActivePrescriptionCount();
        int readyForRefill = systemData.getCurrentPatientReadyForRefillCount();
        int total = systemData.getCurrentPatientTotalMedicationCount();
        
        activeRxLabel.setText("Active: " + active);
        readyForRefillLabel.setText("Ready for Refill: " + readyForRefill);
        totalMedicationsLabel.setText("Total Medications: " + total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryStatsPanel = new javax.swing.JPanel();
        activeRxLabel = new javax.swing.JLabel();
        readyForRefillLabel = new javax.swing.JLabel();
        totalMedicationsLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        statusFilterComboBox = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionsTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rxNumberValueLabel = new javax.swing.JLabel();
        medicationNameValueLabel = new javax.swing.JLabel();
        dosageValueLabel = new javax.swing.JLabel();
        doctorValueLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        refillsValueLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pharmacyValueLabel = new javax.swing.JLabel();
        coverageValueLabel = new javax.swing.JLabel();
        copayValueLabel = new javax.swing.JLabel();
        requestRefillButton = new javax.swing.JButton();
        viewHistoryButton = new javax.swing.JButton();
        contactPharmacyButton = new javax.swing.JButton();

        summaryStatsPanel.setLayout(new java.awt.BorderLayout());

        activeRxLabel.setText("Active:  3");

        readyForRefillLabel.setText("Ready for Refill: 1");

        totalMedicationsLabel.setText("Total Medications: 4");

        jLabel4.setText("Filter by Status:");

        statusFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        prescriptionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Rx #", "Medication", "Dosage", "Quantity", "Refills Left", "Prescribed Date", "Pharmacy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prescriptionsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prescriptionsTable);

        jLabel5.setText("Prescription Details");

        jLabel6.setText("RX Number:");

        jLabel7.setText("Medication:");

        jLabel8.setText("Dosage:");

        jLabel9.setText("Prescribing Doctor:");

        rxNumberValueLabel.setText("Select a prescription to view details");

        medicationNameValueLabel.setText("--");

        dosageValueLabel.setText("--");

        doctorValueLabel.setText("--");

        jLabel14.setText("REfills Remaining:");

        refillsValueLabel.setText("--");

        jLabel16.setText("Pharmacy:");

        jLabel17.setText("Insurance Coverage:");

        jLabel18.setText("Patient Copay:");

        pharmacyValueLabel.setText("--");

        coverageValueLabel.setText("--");

        copayValueLabel.setText("--");

        requestRefillButton.setText("Request Refill");
        requestRefillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestRefillButtonActionPerformed(evt);
            }
        });

        viewHistoryButton.setText("View History");
        viewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryButtonActionPerformed(evt);
            }
        });

        contactPharmacyButton.setText("Contact Pharmacy");
        contactPharmacyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactPharmacyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(summaryStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(activeRxLabel)
                        .addGap(59, 59, 59)
                        .addComponent(readyForRefillLabel)
                        .addGap(29, 29, 29)
                        .addComponent(totalMedicationsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(statusFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(refreshButton))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rxNumberValueLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(medicationNameValueLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dosageValueLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(doctorValueLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(refillsValueLabel)))
                                        .addGap(191, 191, 191)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pharmacyValueLabel))
                                            .addComponent(jLabel17)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(copayValueLabel)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coverageValueLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(requestRefillButton)
                        .addGap(27, 27, 27)
                        .addComponent(viewHistoryButton)
                        .addGap(30, 30, 30)
                        .addComponent(contactPharmacyButton)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(summaryStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activeRxLabel)
                    .addComponent(readyForRefillLabel)
                    .addComponent(totalMedicationsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(statusFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rxNumberValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(medicationNameValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dosageValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(doctorValueLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(pharmacyValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(coverageValueLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(refillsValueLabel)
                    .addComponent(jLabel18)
                    .addComponent(copayValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestRefillButton)
                    .addComponent(viewHistoryButton)
                    .addComponent(contactPharmacyButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void viewHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryButtonActionPerformed
        // TODO add your handling code here:
        if (rxNumberValueLabel.getText().equals("Select a prescription to view details")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a prescription from the table first!",
                "No Prescription Selected",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Prescription Refill History for " + rxNumberValueLabel.getText() + ":\n\n" +
                "1. Filled on 11/15/2025 at CVS Pharmacy - Main St\n" +
                "2. Filled on 10/15/2025 at CVS Pharmacy - Main St\n" +
                "3. Filled on 09/15/2025 at CVS Pharmacy - Main St\n" +
                "4. Initial fill on 08/15/2025 at CVS Pharmacy - Main St",
                "Prescription History",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_viewHistoryButtonActionPerformed

    private void prescriptionsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionsTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = prescriptionsTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            String rxNumber = prescriptionsTable.getValueAt(selectedRow, 0).toString();
            
            business.SystemData systemData = business.SystemData.getInstance();
            model.Prescription rx = systemData.getPrescriptionDirectory().findPrescriptionByNumber(rxNumber);
            
            if (rx != null) {
                // Update detail labels
                rxNumberValueLabel.setText(rx.getPrescriptionNumber());
                medicationNameValueLabel.setText("Medication: " + rx.getDosage());
                dosageValueLabel.setText(rx.getDosage());
                doctorValueLabel.setText("Dr. Sarah Johnson, MD");
                refillsValueLabel.setText(rx.getRefillStatusMessage());
                pharmacyValueLabel.setText("CVS Pharmacy - Main St");
                coverageValueLabel.setText("80% covered (Tier 1)");
                copayValueLabel.setText("$10.00");
                
                // Color code refills
                if (rx.getRefillsRemaining() == 0) {
                    refillsValueLabel.setForeground(new java.awt.Color(220, 53, 69)); // Red
                } else if (rx.getRefillsRemaining() <= 1) {
                    refillsValueLabel.setForeground(new java.awt.Color(255, 152, 0)); // Orange
                } else {
                    refillsValueLabel.setForeground(new java.awt.Color(40, 167, 69)); // Green
                }
            }
        }
    }//GEN-LAST:event_prescriptionsTableMouseClicked

    private void requestRefillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestRefillButtonActionPerformed
        // TODO add your handling code here:
         if (rxNumberValueLabel.getText().equals("Select a prescription to view details")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a prescription from the table first!",
                "No Prescription Selected",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String rxNumber = rxNumberValueLabel.getText();
        business.SystemData systemData = business.SystemData.getInstance();
        model.Prescription rx = systemData.getPrescriptionDirectory().findPrescriptionByNumber(rxNumber);
        
        if (rx == null) {
            return;
        }
        
        // Check if can refill
        if (!rx.canRefill()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No refills remaining for this prescription.\n\n" +
                "Please contact your doctor to renew your prescription.",
                "No Refills Available",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirm refill
        int response = javax.swing.JOptionPane.showConfirmDialog(this,
            "Request refill for:\n\n" +
            "Medication: " + rx.getDosage() + "\n" +
            "Pharmacy: " + pharmacyValueLabel.getText() + "\n" +
            "Patient Copay: " + copayValueLabel.getText() + "\n\n" +
            "Do you want to proceed?",
            "Request Refill",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);
        
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            // Process refill
            boolean success = systemData.requestRefill(rxNumber);
            
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Refill request submitted successfully!\n\n" +
                    "Your prescription will be ready for pickup at:\n" +
                    pharmacyValueLabel.getText() + "\n\n" +
                    "Expected ready time: Today by 5:00 PM\n\n" +
                    "You will receive a text notification when ready.",
                    "Refill Requested",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                // Reload table and stats
                loadPrescriptions();
                updateStatistics();
                
                // Refresh selected row details
                int selectedRow = prescriptionsTable.getSelectedRow();
                if (selectedRow >= 0) {
                    prescriptionsTableMouseClicked(null);
                }
            }
        }
    }//GEN-LAST:event_requestRefillButtonActionPerformed

    private void contactPharmacyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactPharmacyButtonActionPerformed
        // TODO add your handling code here:
         if (rxNumberValueLabel.getText().equals("Select a prescription to view details")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a prescription from the table first!",
                "No Prescription Selected",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pharmacy Contact Information:\n\n" +
                pharmacyValueLabel.getText() + "\n\n" +
                "Phone: (555) 123-4567\n" +
                "Hours: Mon-Fri 9AM-9PM, Sat-Sun 10AM-6PM\n" +
                "Address: 123 Main Street, Boston, MA 02108\n\n" +
                "Pharmacist on duty: Michael Chen, PharmD",
                "Contact Pharmacy",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_contactPharmacyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeRxLabel;
    private javax.swing.JButton contactPharmacyButton;
    private javax.swing.JLabel copayValueLabel;
    private javax.swing.JLabel coverageValueLabel;
    private javax.swing.JLabel doctorValueLabel;
    private javax.swing.JLabel dosageValueLabel;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel medicationNameValueLabel;
    private javax.swing.JLabel pharmacyValueLabel;
    private javax.swing.JTable prescriptionsTable;
    private javax.swing.JLabel readyForRefillLabel;
    private javax.swing.JLabel refillsValueLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton requestRefillButton;
    private javax.swing.JLabel rxNumberValueLabel;
    private javax.swing.JComboBox<String> statusFilterComboBox;
    private javax.swing.JPanel summaryStatsPanel;
    private javax.swing.JLabel totalMedicationsLabel;
    private javax.swing.JButton viewHistoryButton;
    // End of variables declaration//GEN-END:variables
}
