/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class PatientRecordsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientRecordsPanel
     */
    public PatientRecordsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        patientIdTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        dobValueLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bloodTypeValueLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        allergiesValueLabel = new javax.swing.JLabel();
        recordTypeLabel = new javax.swing.JLabel();
        recordTypeComboBox = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        recordsScrollPane = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        viewDetailsButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Medical Records");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel2.setText("View patient medical history and records");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Patient"));

        jLabel3.setText("Patient ID: *");

        searchButton.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addComponent(patientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(searchButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(patientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(searchButton))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 740, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Information"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, -1, -1));

        jLabel5.setText("DOB:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 46, -1, -1));

        nameValueLabel.setText("Div Div");
        jPanel2.add(nameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 24, -1, -1));

        dobValueLabel.setText("01/15/1978 (Age: 46)");
        jPanel2.add(dobValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 46, -1, -1));

        jLabel6.setText("Blood Type:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 68, -1, -1));

        bloodTypeValueLabel.setText("O+");
        jPanel2.add(bloodTypeValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 68, -1, -1));

        jLabel7.setText("Allergies:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 90, -1, -1));

        allergiesValueLabel.setText("Penicillin, Peanuts");
        jPanel2.add(allergiesValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 90, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 740, 120));

        recordTypeLabel.setText("Record Type:");
        add(recordTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        recordTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Records", "Prescriptions", "Lab Results", "Diagnoses", "Procedures" }));
        add(recordTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        refreshButton.setText("Refresh");
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Type", "Description", "Provider", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordsScrollPane.setViewportView(recordsTable);

        add(recordsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 740, 200));

        viewDetailsButton.setText("View Details");
        add(viewDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        printButton.setText("Print Records");
        add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allergiesValueLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bloodTypeValueLabel;
    private javax.swing.JLabel dobValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JTextField patientIdTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JComboBox<String> recordTypeComboBox;
    private javax.swing.JLabel recordTypeLabel;
    private javax.swing.JScrollPane recordsScrollPane;
    private javax.swing.JTable recordsTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables
}
