/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class PatientCheckInPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientCheckInPanel
     */
    public PatientCheckInPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchMethodLabel = new javax.swing.JLabel();
        searchMethodComboBox = new javax.swing.JComboBox<>();
        searchValueLabel = new javax.swing.JLabel();
        searchValueTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        patientInfoPanel = new javax.swing.JPanel();
        patientIdLabel = new javax.swing.JLabel();
        patientIdValueLabel = new javax.swing.JLabel();
        patientNameLabel = new javax.swing.JLabel();
        patientNameValueLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        dobValueLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phoneValueLabel = new javax.swing.JLabel();
        insuranceLabel = new javax.swing.JLabel();
        insuranceValueLabel = new javax.swing.JLabel();
        policyNumberLabel = new javax.swing.JLabel();
        policyNumberValueLabel = new javax.swing.JLabel();
        verifyInsuranceButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        reasonLabel = new javax.swing.JLabel();
        reasonComboBox = new javax.swing.JComboBox<>();
        notesLabel = new javax.swing.JLabel();
        notesTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        checkInButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setText("Patient Check-In");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 9, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 6, -1, -1));

        jLabel1.setText("Check in patients for appointments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 35, -1, -1));

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Patient"));

        searchMethodLabel.setText("Search By");

        searchMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient ID", "Name", "Phone" }));

        searchValueLabel.setText("Enter Value:");

        searchButton.setText("Search");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchMethodLabel)
                    .addComponent(searchValueLabel))
                .addGap(187, 187, 187)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchMethodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchValueTextField))
                .addGap(40, 40, 40)
                .addComponent(searchButton)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchMethodLabel)
                    .addComponent(searchMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchValueLabel)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton)))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 85, 740, 110));

        patientInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Information"));

        patientIdLabel.setText("Patient ID:");

        patientIdValueLabel.setText("P-12345");

        patientNameLabel.setText("Name:");

        patientNameValueLabel.setText("Div Div");

        dobLabel.setText("Date of Birth:");

        dobValueLabel.setText("01/15/1978 (Age: 46)");

        phoneLabel.setText("Phone:");

        phoneValueLabel.setText("(555) 123-4567");

        insuranceLabel.setText("Insurance:");

        insuranceValueLabel.setText("BlueCross PPO - Active");

        policyNumberLabel.setText("Policy Number:");

        policyNumberValueLabel.setText("POL-2024-00123");

        verifyInsuranceButton.setText("Verify Insurance");

        javax.swing.GroupLayout patientInfoPanelLayout = new javax.swing.GroupLayout(patientInfoPanel);
        patientInfoPanel.setLayout(patientInfoPanelLayout);
        patientInfoPanelLayout.setHorizontalGroup(
            patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientInfoPanelLayout.createSequentialGroup()
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientInfoPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdLabel)
                            .addComponent(patientNameLabel)
                            .addComponent(dobLabel)
                            .addComponent(phoneLabel)
                            .addComponent(insuranceLabel)
                            .addComponent(policyNumberLabel))
                        .addGap(110, 110, 110)
                        .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(policyNumberValueLabel)
                            .addComponent(insuranceValueLabel)
                            .addComponent(phoneValueLabel)
                            .addComponent(dobValueLabel)
                            .addComponent(patientNameValueLabel)
                            .addComponent(patientIdValueLabel)))
                    .addGroup(patientInfoPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(verifyInsuranceButton)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        patientInfoPanelLayout.setVerticalGroup(
            patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLabel)
                    .addComponent(patientIdValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(patientNameValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceLabel)
                    .addComponent(insuranceValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyNumberLabel)
                    .addComponent(policyNumberValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verifyInsuranceButton)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        add(patientInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 740, 230));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Check-In Details"));

        reasonLabel.setText("Reason for Visit:");

        reasonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annual Checkup", "Follow-up", "Consultation", "Emergency", "Lab Results", "Prescription Refill" }));

        notesLabel.setText("Additional Notes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reasonLabel)
                    .addComponent(notesLabel))
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reasonComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notesTextField))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonLabel)
                    .addComponent(reasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notesLabel)
                    .addComponent(notesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 740, 90));

        clearButton.setText("Clear");
        add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, -1));

        checkInButton.setText("Check In Patient");
        add(checkInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel dobValueLabel;
    private javax.swing.JLabel insuranceLabel;
    private javax.swing.JLabel insuranceValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JTextField notesTextField;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JLabel patientIdValueLabel;
    private javax.swing.JPanel patientInfoPanel;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel patientNameValueLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneValueLabel;
    private javax.swing.JLabel policyNumberLabel;
    private javax.swing.JLabel policyNumberValueLabel;
    private javax.swing.JComboBox<String> reasonComboBox;
    private javax.swing.JLabel reasonLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchMethodComboBox;
    private javax.swing.JLabel searchMethodLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel searchValueLabel;
    private javax.swing.JTextField searchValueTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton verifyInsuranceButton;
    // End of variables declaration//GEN-END:variables
}
