/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class PatientDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientDashboardPanel
     */
    public PatientDashboardPanel() {
        initComponents();
        loadDashboardStats();
    }
    
    /**
     * Load real statistics for current patient
     */
    private void loadDashboardStats() {
        business.SystemData systemData = business.SystemData.getInstance();
        
        // Get real counts from SystemData
        int activePolicies = systemData.getCurrentPatientActivePolicyCount();
        int pendingClaims = systemData.getCurrentPatientPendingClaimCount();
        int activePrescriptions = systemData.getCurrentPatientActivePrescriptionCount();
        
        // Update the stat card labels with real data
        activePoliciesCountLabel.setText(String.valueOf(activePolicies));
        pendingClaimsCountLabel.setText(String.valueOf(pendingClaims));
        activePrescriptionsCountLabel.setText(String.valueOf(activePrescriptions));
        
        // Update welcome message with real user name
        String userName = systemData.getCurrentUserFullName();
        welcomePatientLabel.setText("Welcome, " + userName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        navigationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardHomeButton = new javax.swing.JButton();
        myPoliciesButton = new javax.swing.JButton();
        submitClaimButton = new javax.swing.JButton();
        myClaimsButton = new javax.swing.JButton();
        myPrescriptionsButton = new javax.swing.JButton();
        findPharmacyButton = new javax.swing.JButton();
        myProfileButton = new javax.swing.JButton();
        workspacePanel = new javax.swing.JPanel();
        welcomeDashboardPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quickSubmitClaimButton = new javax.swing.JButton();
        activePoliciesCard = new javax.swing.JPanel();
        activePoliciesCountLabel = new javax.swing.JLabel();
        activePoliciesTextLabel = new javax.swing.JLabel();
        quickViewPrescriptionsButton = new javax.swing.JButton();
        welcomePatientLabel = new javax.swing.JLabel();
        pendingClaimsCard = new javax.swing.JPanel();
        pendingClaimsCountLabel = new javax.swing.JLabel();
        pendingClaimsTextLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        activePrescriptionsCard = new javax.swing.JPanel();
        activePrescriptionsCountLabel = new javax.swing.JLabel();
        activePrescriptionsTextLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PATIENT MENU");

        dashboardHomeButton.setText("Dashboard Home");
        dashboardHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardHomeButtonActionPerformed(evt);
            }
        });

        myPoliciesButton.setText("My Policies");
        myPoliciesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPoliciesButtonActionPerformed(evt);
            }
        });

        submitClaimButton.setText("Submit Claim");
        submitClaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitClaimButtonActionPerformed(evt);
            }
        });

        myClaimsButton.setText("My Claims");
        myClaimsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myClaimsButtonActionPerformed(evt);
            }
        });

        myPrescriptionsButton.setText("My Prescriptions");
        myPrescriptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPrescriptionsButtonActionPerformed(evt);
            }
        });

        findPharmacyButton.setText("Find Pharmacy");
        findPharmacyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPharmacyButtonActionPerformed(evt);
            }
        });

        myProfileButton.setText("Profile");
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myProfileButton)
                    .addComponent(findPharmacyButton)
                    .addComponent(myPrescriptionsButton)
                    .addComponent(myClaimsButton)
                    .addComponent(submitClaimButton)
                    .addComponent(jLabel1)
                    .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(myPoliciesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashboardHomeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(dashboardHomeButton)
                .addGap(18, 18, 18)
                .addComponent(myPoliciesButton)
                .addGap(18, 18, 18)
                .addComponent(submitClaimButton)
                .addGap(18, 18, 18)
                .addComponent(myClaimsButton)
                .addGap(18, 18, 18)
                .addComponent(myPrescriptionsButton)
                .addGap(18, 18, 18)
                .addComponent(findPharmacyButton)
                .addGap(18, 18, 18)
                .addComponent(myProfileButton)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(navigationPanel);

        workspacePanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Welcome to Your Patient Dashboard ");

        jLabel5.setText("Quick Actions");

        jLabel3.setText("Manage your insurance policies, submit claims, track Rx ");

        quickSubmitClaimButton.setText("Submit New Claim");
        quickSubmitClaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSubmitClaimButtonActionPerformed(evt);
            }
        });

        activePoliciesCard.setBackground(new java.awt.Color(153, 255, 255));

        activePoliciesCountLabel.setText("2");

        activePoliciesTextLabel.setText("Active Policies");

        javax.swing.GroupLayout activePoliciesCardLayout = new javax.swing.GroupLayout(activePoliciesCard);
        activePoliciesCard.setLayout(activePoliciesCardLayout);
        activePoliciesCardLayout.setHorizontalGroup(
            activePoliciesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activePoliciesCardLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(activePoliciesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activePoliciesCardLayout.createSequentialGroup()
                        .addComponent(activePoliciesTextLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activePoliciesCardLayout.createSequentialGroup()
                        .addComponent(activePoliciesCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        activePoliciesCardLayout.setVerticalGroup(
            activePoliciesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activePoliciesCardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(activePoliciesCountLabel)
                .addGap(18, 18, 18)
                .addComponent(activePoliciesTextLabel)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        quickViewPrescriptionsButton.setText("View Prescriptions");
        quickViewPrescriptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickViewPrescriptionsButtonActionPerformed(evt);
            }
        });

        welcomePatientLabel.setText("Welcome, Patient");

        pendingClaimsCard.setBackground(new java.awt.Color(153, 255, 255));

        pendingClaimsCountLabel.setText("1");

        pendingClaimsTextLabel.setText("Pending Claims");

        javax.swing.GroupLayout pendingClaimsCardLayout = new javax.swing.GroupLayout(pendingClaimsCard);
        pendingClaimsCard.setLayout(pendingClaimsCardLayout);
        pendingClaimsCardLayout.setHorizontalGroup(
            pendingClaimsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingClaimsCardLayout.createSequentialGroup()
                .addGroup(pendingClaimsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pendingClaimsCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pendingClaimsTextLabel))
                    .addGroup(pendingClaimsCardLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pendingClaimsCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pendingClaimsCardLayout.setVerticalGroup(
            pendingClaimsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingClaimsCardLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pendingClaimsCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pendingClaimsTextLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        logoutButton.setText("Logout");

        activePrescriptionsCard.setBackground(new java.awt.Color(153, 255, 255));

        activePrescriptionsCountLabel.setText("3");

        activePrescriptionsTextLabel.setText("Active Prescriptions");

        javax.swing.GroupLayout activePrescriptionsCardLayout = new javax.swing.GroupLayout(activePrescriptionsCard);
        activePrescriptionsCard.setLayout(activePrescriptionsCardLayout);
        activePrescriptionsCardLayout.setHorizontalGroup(
            activePrescriptionsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activePrescriptionsCardLayout.createSequentialGroup()
                .addGroup(activePrescriptionsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activePrescriptionsCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(activePrescriptionsTextLabel))
                    .addGroup(activePrescriptionsCardLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(activePrescriptionsCountLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        activePrescriptionsCardLayout.setVerticalGroup(
            activePrescriptionsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activePrescriptionsCardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(activePrescriptionsCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activePrescriptionsTextLabel)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout welcomeDashboardPanelLayout = new javax.swing.GroupLayout(welcomeDashboardPanel);
        welcomeDashboardPanel.setLayout(welcomeDashboardPanelLayout);
        welcomeDashboardPanelLayout.setHorizontalGroup(
            welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeDashboardPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomeDashboardPanelLayout.createSequentialGroup()
                        .addComponent(quickSubmitClaimButton)
                        .addGap(61, 61, 61)
                        .addComponent(quickViewPrescriptionsButton))
                    .addComponent(jLabel5)
                    .addGroup(welcomeDashboardPanelLayout.createSequentialGroup()
                        .addComponent(activePoliciesCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(pendingClaimsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(activePrescriptionsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(welcomePatientLabel)
                        .addComponent(jLabel3)))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeDashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(178, 178, 178))
        );
        welcomeDashboardPanelLayout.setVerticalGroup(
            welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeDashboardPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomePatientLabel)
                    .addComponent(logoutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activePoliciesCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingClaimsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activePrescriptionsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(welcomeDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quickSubmitClaimButton)
                    .addComponent(quickViewPrescriptionsButton))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        workspacePanel.add(welcomeDashboardPanel, "card2");

        jSplitPane1.setRightComponent(workspacePanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

     private void dashboardHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardHomeButtonActionPerformed
        // Set welcome panel back to right side of split pane
        jSplitPane1.setRightComponent(welcomeDashboardPanel);
        jSplitPane1.revalidate();
        jSplitPane1.repaint();
    }//GEN-LAST:event_dashboardHomeButtonActionPerformed
    
    private void myPoliciesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPoliciesButtonActionPerformed
        // Create MyPoliciesPanel
        MyPoliciesPanel panel = new MyPoliciesPanel();
        
        // Set as right component of split pane
        jSplitPane1.setRightComponent(panel);
        jSplitPane1.revalidate();
        jSplitPane1.repaint();
    }//GEN-LAST:event_myPoliciesButtonActionPerformed

    private void submitClaimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitClaimButtonActionPerformed
        // Create SubmitClaimPanel
        SubmitClaimPanel panel = new SubmitClaimPanel();
        
        // Set as right component of split pane
        jSplitPane1.setRightComponent(panel);
        jSplitPane1.revalidate();
        jSplitPane1.repaint();
    }//GEN-LAST:event_submitClaimButtonActionPerformed

    private void myClaimsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myClaimsButtonActionPerformed
        // Create MyClaimsPanel
        MyClaimsPanel panel = new MyClaimsPanel();
        
        // Set as right component of split pane
        jSplitPane1.setRightComponent(panel);
        jSplitPane1.revalidate();
        jSplitPane1.repaint();
    }//GEN-LAST:event_myClaimsButtonActionPerformed

    private void myPrescriptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPrescriptionsButtonActionPerformed
        // Create MyPrescriptionsPanel
        MyPrescriptionsPanel panel = new MyPrescriptionsPanel();
        
        // Set as right component of split pane
        jSplitPane1.setRightComponent(panel);
        jSplitPane1.revalidate();
        jSplitPane1.repaint();
    }//GEN-LAST:event_myPrescriptionsButtonActionPerformed

    private void findPharmacyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPharmacyButtonActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "Find Pharmacy feature coming soon!",
            "Coming Soon",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_findPharmacyButtonActionPerformed

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "My Profile feature coming soon!",
            "Coming Soon",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_myProfileButtonActionPerformed
    
    private void quickSubmitClaimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSubmitClaimButtonActionPerformed
        submitClaimButtonActionPerformed(evt);
    }//GEN-LAST:event_quickSubmitClaimButtonActionPerformed

    private void quickViewPrescriptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickViewPrescriptionsButtonActionPerformed
        myPrescriptionsButtonActionPerformed(evt);
    }//GEN-LAST:event_quickViewPrescriptionsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activePoliciesCard;
    private javax.swing.JPanel activePoliciesCard10;
    private javax.swing.JPanel activePoliciesCard11;
    private javax.swing.JPanel activePoliciesCard12;
    private javax.swing.JPanel activePoliciesCard13;
    private javax.swing.JPanel activePoliciesCard9;
    private javax.swing.JLabel activePoliciesCountLabel;
    private javax.swing.JLabel activePoliciesCountLabel10;
    private javax.swing.JLabel activePoliciesCountLabel11;
    private javax.swing.JLabel activePoliciesCountLabel12;
    private javax.swing.JLabel activePoliciesCountLabel13;
    private javax.swing.JLabel activePoliciesCountLabel9;
    private javax.swing.JLabel activePoliciesTextLabel;
    private javax.swing.JLabel activePoliciesTextLabel10;
    private javax.swing.JLabel activePoliciesTextLabel11;
    private javax.swing.JLabel activePoliciesTextLabel12;
    private javax.swing.JLabel activePoliciesTextLabel13;
    private javax.swing.JLabel activePoliciesTextLabel9;
    private javax.swing.JPanel activePrescriptionsCard;
    private javax.swing.JLabel activePrescriptionsCountLabel;
    private javax.swing.JLabel activePrescriptionsTextLabel;
    private javax.swing.JButton dashboardHomeButton;
    private javax.swing.JButton findPharmacyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myClaimsButton;
    private javax.swing.JButton myPoliciesButton;
    private javax.swing.JButton myPrescriptionsButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPanel pendingClaimsCard;
    private javax.swing.JLabel pendingClaimsCountLabel;
    private javax.swing.JLabel pendingClaimsTextLabel;
    private javax.swing.JButton quickSubmitClaimButton;
    private javax.swing.JButton quickViewPrescriptionsButton;
    private javax.swing.JButton submitClaimButton;
    private javax.swing.JPanel welcomeDashboardPanel;
    private javax.swing.JLabel welcomePatientLabel;
    private javax.swing.JPanel workspacePanel;
    // End of variables declaration//GEN-END:variables
}
