/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class PriorAuthorizationRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form PriorAuthorizationRequestPanel
     */
    public PriorAuthorizationRequestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        patientIdTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        patientNameLabel = new javax.swing.JLabel();
        patientNameValueLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insuranceValueLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        requestTypeLabel = new javax.swing.JLabel();
        requestTypeComboBox = new javax.swing.JComboBox<>();
        procedureNameLabel = new javax.swing.JLabel();
        procedureNameTextField = new javax.swing.JTextField();
        diagnosisLabel = new javax.swing.JLabel();
        diagnosisTextField = new javax.swing.JTextField();
        justificationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        justificationTextArea = new javax.swing.JTextArea();
        urgencyLabel = new javax.swing.JLabel();
        urgencyComboBox = new javax.swing.JComboBox<>();
        documentPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Prior Authorization Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 6, -1, -1));

        jLabel2.setText("Request prior authorization for procedures/medications");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Information"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Patient ID: *");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));
        jPanel2.add(patientIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 24, 110, -1));

        searchButton.setText("Search");
        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 24, -1, -1));

        patientNameLabel.setText("Patient Name:");
        jPanel2.add(patientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 53, -1, -1));

        patientNameValueLabel.setText("Div Div");
        jPanel2.add(patientNameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 53, -1, -1));

        jLabel4.setText("Insurance:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 75, -1, -1));

        insuranceValueLabel.setText("BlueCross PPO - Active");
        jPanel2.add(insuranceValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 75, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 740, 100));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Authorization Request Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTypeLabel.setText("Request Type: *");
        jPanel1.add(requestTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));

        requestTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Procedure", "Medication", "Medical Equipment", "Hospital Admission", "Surgery" }));
        jPanel1.add(requestTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 24, -1, -1));

        procedureNameLabel.setText("Procedure/Item Name: *");
        jPanel1.add(procedureNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 58, -1, -1));
        jPanel1.add(procedureNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 58, 137, -1));

        diagnosisLabel.setText("Diagnosis Code: *");
        jPanel1.add(diagnosisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 86, -1, -1));
        jPanel1.add(diagnosisTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 86, 137, -1));

        justificationLabel.setText("Medical Justification: *");
        jPanel1.add(justificationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 120, -1, -1));

        justificationTextArea.setColumns(20);
        justificationTextArea.setLineWrap(true);
        justificationTextArea.setRows(5);
        justificationTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(justificationTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 710, 90));

        urgencyLabel.setText("Urgency Level: *");
        jPanel1.add(urgencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        urgencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Urgent", "Emergency" }));
        jPanel1.add(urgencyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 740, 280));

        documentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Supporting Documents:");
        documentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 9, -1, -1));

        uploadButton.setText("Upload Document");
        documentPanel.add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, -1, -1));

        add(documentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 740, 30));

        clearButton.setText("Clear");
        add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        submitButton.setText("Submit Request");
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JTextField diagnosisTextField;
    private javax.swing.JPanel documentPanel;
    private javax.swing.JLabel insuranceValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel justificationLabel;
    private javax.swing.JTextArea justificationTextArea;
    private javax.swing.JTextField patientIdTextField;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel patientNameValueLabel;
    private javax.swing.JLabel procedureNameLabel;
    private javax.swing.JTextField procedureNameTextField;
    private javax.swing.JComboBox<String> requestTypeComboBox;
    private javax.swing.JLabel requestTypeLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton uploadButton;
    private javax.swing.JComboBox<String> urgencyComboBox;
    private javax.swing.JLabel urgencyLabel;
    // End of variables declaration//GEN-END:variables
}
