/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class ProcessPurchaseOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessPurchaseOrderPanel
     */
    public ProcessPurchaseOrderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        orderInfoPanel = new javax.swing.JPanel();
        orderIdLabel = new javax.swing.JLabel();
        orderIdValueLabel = new javax.swing.JLabel();
        pharmacyLabel = new javax.swing.JLabel();
        pharmacyValueLabel = new javax.swing.JLabel();
        orderDateLabel = new javax.swing.JLabel();
        orderDateValueLabel = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        totalAmountValueLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusValueLabel = new javax.swing.JLabel();
        orderItemsLabel = new javax.swing.JLabel();
        itemsScrollPane = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        fulfillmentPanel = new javax.swing.JPanel();
        shippingDateLabel = new javax.swing.JLabel();
        shippingDateField = new javax.swing.JTextField();
        trackingNumberLabel = new javax.swing.JLabel();
        trackingNumberTextField = new javax.swing.JTextField();
        rejectButton = new javax.swing.JButton();
        partialFulfillButton = new javax.swing.JButton();
        completeButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setText("Process Purchase Order");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 6, -1, -1));

        descriptionLabel.setText("Review and fulfill purchase order");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        orderInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Information"));
        orderInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderIdLabel.setText("Order ID:");
        orderInfoPanel.add(orderIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, -1, -1));

        orderIdValueLabel.setText("PO-2024-001");
        orderInfoPanel.add(orderIdValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 18, -1, -1));

        pharmacyLabel.setText("Pharmacy:");
        orderInfoPanel.add(pharmacyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, -1, -1));

        pharmacyValueLabel.setText("CVS Pharmacy - Main Street");
        orderInfoPanel.add(pharmacyValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 40, -1, -1));

        orderDateLabel.setText("Order Date:");
        orderInfoPanel.add(orderDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 62, -1, -1));

        orderDateValueLabel.setText("11/20/2024");
        orderInfoPanel.add(orderDateValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 62, -1, -1));

        totalAmountLabel.setText("Total Amount:");
        orderInfoPanel.add(totalAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 84, -1, -1));

        totalAmountValueLabel.setText("$12,500.00");
        orderInfoPanel.add(totalAmountValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 84, -1, -1));

        statusLabel.setText("Status:");
        orderInfoPanel.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 106, -1, -1));

        statusValueLabel.setText("Pending");
        orderInfoPanel.add(statusValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 106, -1, -1));

        add(orderInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 740, 130));

        orderItemsLabel.setText("Order Items");
        add(orderItemsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Med ID", "Medication", "Quantity", "Unit Price", "Total", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemsTable.setRowHeight(30);
        itemsScrollPane.setViewportView(itemsTable);

        add(itemsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 740, 190));

        fulfillmentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fulfillment Details"));

        shippingDateLabel.setText("Shipping Date: *");

        shippingDateField.setText("[MM/DD/YYYY]");

        trackingNumberLabel.setText("Tracking Number:");

        javax.swing.GroupLayout fulfillmentPanelLayout = new javax.swing.GroupLayout(fulfillmentPanel);
        fulfillmentPanel.setLayout(fulfillmentPanelLayout);
        fulfillmentPanelLayout.setHorizontalGroup(
            fulfillmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fulfillmentPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(fulfillmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shippingDateLabel)
                    .addComponent(trackingNumberLabel))
                .addGap(125, 125, 125)
                .addGroup(fulfillmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trackingNumberTextField)
                    .addComponent(shippingDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        fulfillmentPanelLayout.setVerticalGroup(
            fulfillmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fulfillmentPanelLayout.createSequentialGroup()
                .addGroup(fulfillmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shippingDateLabel)
                    .addComponent(shippingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fulfillmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trackingNumberLabel)
                    .addComponent(trackingNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        add(fulfillmentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 740, 75));

        rejectButton.setText("Reject Order");
        add(rejectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        partialFulfillButton.setText("Partial Fulfill");
        add(partialFulfillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 110, -1));

        completeButton.setText("Complete Order");
        add(completeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton completeButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel fulfillmentPanel;
    private javax.swing.JScrollPane itemsScrollPane;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JLabel orderDateValueLabel;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JLabel orderIdValueLabel;
    private javax.swing.JPanel orderInfoPanel;
    private javax.swing.JLabel orderItemsLabel;
    private javax.swing.JButton partialFulfillButton;
    private javax.swing.JLabel pharmacyLabel;
    private javax.swing.JLabel pharmacyValueLabel;
    private javax.swing.JButton rejectButton;
    private javax.swing.JTextField shippingDateField;
    private javax.swing.JLabel shippingDateLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusValueLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel totalAmountValueLabel;
    private javax.swing.JLabel trackingNumberLabel;
    private javax.swing.JTextField trackingNumberTextField;
    // End of variables declaration//GEN-END:variables
}
