/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Sandeep Patil
 */
public class SubmitClaimPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubmitClaimPanel
     */
    public SubmitClaimPanel() {
        initComponents();
        loadPoliciesIntoDropdown();
    }

    /**
     * Load active policies into policy dropdown
     */
    private void loadPoliciesIntoDropdown() {
        // Get SystemData
        business.SystemData systemData = business.SystemData.getInstance();

        // Clear existing items
        policyComboBox.removeAllItems();

        // Add default option
        policyComboBox.addItem("-- Select Policy --");

        // Get active policies for current patient
        java.util.List<model.Policy> activePolicies = systemData.getCurrentPatientActivePolicies();

        // Add each policy to dropdown
        for (model.Policy policy : activePolicies) {
            policyComboBox.addItem(policy.getPolicyNumber() + " - " + policy.getPolicyType().getDisplayName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        claimFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        policyComboBox = new javax.swing.JComboBox<>();
        serviceDateTextField = new javax.swing.JTextField();
        providerNameTextField = new javax.swing.JTextField();
        diagnosisTextField = new javax.swing.JTextField();
        serviceTypeComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        claimAmountTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        additionalNotesTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        uploadDocumentButton = new javax.swing.JButton();
        uploadedFilesLabel = new javax.swing.JLabel();
        submitClaimButton = new javax.swing.JButton();
        clearFormButton = new javax.swing.JButton();

        claimFormPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Claim Information");

        jLabel2.setText("Select Policy:");

        jLabel3.setText("Service Date:");

        jLabel4.setText("Provider Name:");

        jLabel5.setText("Diagnosis/Reason:");

        jLabel6.setText("Service Type:");

        policyComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        serviceDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceDateTextFieldActionPerformed(evt);
            }
        });

        diagnosisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisTextFieldActionPerformed(evt);
            }
        });

        serviceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Doctor Visit", "ER Visit", "Hospital Stay", "Surgery", "Others" }));

        jLabel7.setText("Claim Amount ($):");

        jLabel8.setText("Additional Notes:");

        additionalNotesTextArea.setColumns(20);
        additionalNotesTextArea.setRows(5);
        jScrollPane1.setViewportView(additionalNotesTextArea);

        jLabel9.setText("Supporting Documents:");

        uploadDocumentButton.setText("Upload Documents");
        uploadDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadDocumentButtonActionPerformed(evt);
            }
        });

        uploadedFilesLabel.setText("No Uploaded Files");

        submitClaimButton.setText("Submit Form");
        submitClaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitClaimButtonActionPerformed(evt);
            }
        });

        clearFormButton.setText("Clear Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(claimFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(272, 272, 272))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(serviceTypeComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(policyComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel1)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel4)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(providerNameTextField))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel3)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(serviceDateTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                133,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel7)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(claimAmountTextField))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel5)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(diagnosisTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                134,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(uploadedFilesLabel)
                                                        .addComponent(uploadDocumentButton)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(submitClaimButton)
                                                .addGap(40, 40, 40)
                                                .addComponent(clearFormButton)))
                                .addContainerGap(368, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(policyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(serviceDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(providerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(diagnosisTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(serviceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(claimAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14,
                                        Short.MAX_VALUE)
                                .addComponent(claimFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(uploadDocumentButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadedFilesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(submitClaimButton)
                                        .addComponent(clearFormButton))
                                .addGap(16, 16, 16)));
    }// </editor-fold>//GEN-END:initComponents

    private void uploadDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_uploadDocumentButtonActionPerformed
        // Open file chooser
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Select Claim Document");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Text Files (for auto-fill)", "txt"));

        int result = fileChooser.showOpenDialog(this);

        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            uploadedFilesLabel.setText("Uploaded: " + selectedFile.getName());

            // Try to parse and auto-fill claim data
            try {
                java.util.Map<String, String> claimData = utils.ClaimDocumentParser.parseClaimDocument(selectedFile);

                if (utils.ClaimDocumentParser.isValidClaimData(claimData)) {
                    // Auto-fill form fields
                    autoFillFormFields(claimData);

                    uploadedFilesLabel.setText("✓ " + selectedFile.getName() + " (Data auto-filled)");
                    uploadedFilesLabel.setForeground(new java.awt.Color(40, 167, 69)); // Green

                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Claim data extracted successfully!\\n" +
                                    "Please review and verify all auto-filled information.",
                            "Auto-Fill Complete",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    uploadedFilesLabel.setText("⚠ " + selectedFile.getName() + " (No data found)");
                    uploadedFilesLabel.setForeground(new java.awt.Color(255, 152, 0)); // Orange
                }
            } catch (Exception e) {
                uploadedFilesLabel.setText("✗ " + selectedFile.getName() + " (Parse failed)");
                uploadedFilesLabel.setForeground(new java.awt.Color(220, 53, 69)); // Red

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Could not extract data from document.\\n" +
                                "Error: " + e.getMessage(),
                        "Parse Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }// GEN-LAST:event_uploadDocumentButtonActionPerformed

    /**
     * Auto-fill form fields from parsed claim data
     */
    private void autoFillFormFields(java.util.Map<String, String> claimData) {
        // Service Date
        if (claimData.containsKey("serviceDate")) {
            serviceDateTextField.setText(claimData.get("serviceDate"));
        }

        // Provider Name
        if (claimData.containsKey("providerName")) {
            providerNameTextField.setText(claimData.get("providerName"));
        }

        // Diagnosis
        if (claimData.containsKey("diagnosis")) {
            diagnosisTextField.setText(claimData.get("diagnosis"));
        }

        // Service Type
        if (claimData.containsKey("serviceType")) {
            String serviceType = claimData.get("serviceType");
            for (int i = 0; i < serviceTypeComboBox.getItemCount(); i++) {
                if (serviceTypeComboBox.getItemAt(i).equals(serviceType)) {
                    serviceTypeComboBox.setSelectedIndex(i);
                    break;
                }
            }
        }

        // Claim Amount
        if (claimData.containsKey("claimAmount")) {
            claimAmountTextField.setText(claimData.get("claimAmount"));
        }
    }

    private void submitClaimButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitClaimButtonActionPerformed
        // TODO add your handling code here:
        // Get all input values
        String selectedPolicy = (String) policyComboBox.getSelectedItem();
        String serviceDate = serviceDateTextField.getText().trim();
        String providerName = providerNameTextField.getText().trim();
        String diagnosis = diagnosisTextField.getText().trim();
        String selectedServiceType = (String) serviceTypeComboBox.getSelectedItem();
        String claimAmountStr = claimAmountTextField.getText().trim();
        String additionalNotes = additionalNotesTextArea.getText().trim();

        // Validate policy selection
        if (selectedPolicy == null || selectedPolicy.equals("-- Select Policy --")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a policy!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate service date
        if (serviceDate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter the service date!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate provider name
        if (providerName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter the provider name!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate diagnosis
        if (diagnosis.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter the diagnosis or reason!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate service type
        if (selectedServiceType == null || selectedServiceType.equals("-- Select Service Type --")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a service type!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate claim amount
        if (claimAmountStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter the claim amount!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parse and validate amount
        double claimAmount;
        try {
            claimAmount = Double.parseDouble(claimAmountStr);
            if (claimAmount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Claim amount must be greater than zero!",
                        "Validation Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid numeric amount!",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parse service date (simple format MM/DD/YYYY)
        java.time.LocalDate serviceDateParsed;
        try {
            String[] dateParts = serviceDate.split("/");
            if (dateParts.length != 3) {
                throw new Exception("Invalid format");
            }
            int month = Integer.parseInt(dateParts[0]);
            int day = Integer.parseInt(dateParts[1]);
            int year = Integer.parseInt(dateParts[2]);
            serviceDateParsed = java.time.LocalDate.of(year, month, day);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid date in format MM/DD/YYYY (e.g., 11/15/2025)",
                    "Invalid Date",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Extract policy number from selection (format: "POL-2024-00123 - Family PPO")
        String policyNumber = selectedPolicy.split(" - ")[0];

        // Convert service type string to enum
        model.Claim.ServiceType serviceType = null;
        switch (selectedServiceType) {
            case "Emergency Room Visit":
                serviceType = model.Claim.ServiceType.EMERGENCY_ROOM;
                break;
            case "Hospital Stay":
                serviceType = model.Claim.ServiceType.HOSPITAL_STAY;
                break;
            case "Surgery":
                serviceType = model.Claim.ServiceType.SURGERY;
                break;
            case "Doctor Visit":
                serviceType = model.Claim.ServiceType.DOCTOR_VISIT;
                break;
            case "Diagnostic Test":
                serviceType = model.Claim.ServiceType.DIAGNOSTIC_TEST;
                break;
            case "Prescription Medication":
                serviceType = model.Claim.ServiceType.PRESCRIPTION_MEDICATION;
                break;
            case "Physical Therapy":
                serviceType = model.Claim.ServiceType.PHYSICAL_THERAPY;
                break;
            default:
                serviceType = model.Claim.ServiceType.OTHER;
                break;
        }

        // Get SystemData and submit claim
        business.SystemData systemData = business.SystemData.getInstance();
        model.Claim newClaim = systemData.submitClaim(policyNumber, serviceDateParsed, providerName,
                diagnosis, serviceType, claimAmount);

        if (newClaim != null) {
            // Show success message
            String message = "Claim submitted successfully!\n\n" +
                    "Claim Number: " + newClaim.getClaimNumber() + "\n" +
                    "Policy: " + selectedPolicy + "\n" +
                    "Provider: " + providerName + "\n" +
                    "Amount: " + newClaim.getFormattedClaimAmount() + "\n\n" +
                    "Status: " + newClaim.getClaimStatus().getDisplayName() + "\n" +
                    "Expected processing time: 5-7 business days\n\n" +
                    "You will receive an email confirmation shortly.";

            javax.swing.JOptionPane.showMessageDialog(this,
                    message,
                    "Claim Submitted",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Clear the form
            clearForm();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Failed to submit claim. Please try again.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_submitClaimButtonActionPerformed

    /**
     * Clear all form fields
     */
    private void clearForm() {
        policyComboBox.setSelectedIndex(0);
        serviceDateTextField.setText("");
        providerNameTextField.setText("");
        diagnosisTextField.setText("");
        serviceTypeComboBox.setSelectedIndex(0);
        claimAmountTextField.setText("");
        additionalNotesTextArea.setText("");
        uploadedFilesLabel.setText("No Uploaded Files");
        uploadedFilesLabel.setForeground(new java.awt.Color(100, 100, 100));
    }// GEN-LAST:event_submitClaimButtonActionPerformed

    private void serviceDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serviceDateTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_serviceDateTextFieldActionPerformed

    private void diagnosisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diagnosisTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_diagnosisTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea additionalNotesTextArea;
    private javax.swing.JTextField claimAmountTextField;
    private javax.swing.JPanel claimFormPanel;
    private javax.swing.JButton clearFormButton;
    private javax.swing.JTextField diagnosisTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> policyComboBox;
    private javax.swing.JTextField providerNameTextField;
    private javax.swing.JTextField serviceDateTextField;
    private javax.swing.JComboBox<String> serviceTypeComboBox;
    private javax.swing.JButton submitClaimButton;
    private javax.swing.JButton uploadDocumentButton;
    private javax.swing.JLabel uploadedFilesLabel;
    // End of variables declaration//GEN-END:variables
}
