/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class SubmitClaimForPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubmitClaimForPatientPanel
     */
    public SubmitClaimForPatientPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        patientInfoPanel = new javax.swing.JPanel();
        patientIdLabel = new javax.swing.JLabel();
        policyLabel = new javax.swing.JLabel();
        patientIdTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        policyComboBox = new javax.swing.JComboBox<>();
        claimDetailsPanel = new javax.swing.JPanel();
        serviceDateLabel = new javax.swing.JLabel();
        serviceDateChooser = new javax.swing.JTextField();
        providerNameLabel = new javax.swing.JLabel();
        providerNameTextField = new javax.swing.JTextField();
        diagnosisLabel = new javax.swing.JLabel();
        diagnosisTextField = new javax.swing.JTextField();
        serviceTypeLabel = new javax.swing.JLabel();
        serviceTypeComboBox = new javax.swing.JComboBox<>();
        claimAmountLabel = new javax.swing.JLabel();
        claimAmountTextField = new javax.swing.JTextField();
        notesLabel = new javax.swing.JLabel();
        notesScrollPane = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        documentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setText("Submit Insurance Claim");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        descriptionLabel.setText("Submit claim on behalf of patient");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        patientInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient & Policy Information"));
        patientInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientIdLabel.setText("Patient ID: *");
        patientInfoPanel.add(patientIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 27, -1, -1));

        policyLabel.setText("Select Policy: *");
        patientInfoPanel.add(policyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 62, -1, -1));
        patientInfoPanel.add(patientIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 24, 100, -1));

        searchButton.setText("Search");
        patientInfoPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 24, 100, -1));

        policyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientInfoPanel.add(policyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 59, -1, -1));

        add(patientInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 740, 100));

        claimDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Claim Details"));
        claimDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceDateLabel.setText("Service Date: *");
        claimDetailsPanel.add(serviceDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, -1, -1));

        serviceDateChooser.setText("MM/DD/YYYY");
        claimDetailsPanel.add(serviceDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 24, 104, -1));

        providerNameLabel.setText("Provider Name: *");
        claimDetailsPanel.add(providerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, -1, -1));
        claimDetailsPanel.add(providerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 52, 104, -1));

        diagnosisLabel.setText("Diagnosis: *");
        claimDetailsPanel.add(diagnosisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 83, -1, -1));
        claimDetailsPanel.add(diagnosisTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 80, 104, -1));

        serviceTypeLabel.setText("Service Type: *");
        claimDetailsPanel.add(serviceTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 111, -1, -1));

        serviceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor Visit", "ER Visit", "Hospital Stay", "Surgery", "Lab Test", "Imaging", "Therapy" }));
        claimDetailsPanel.add(serviceTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 108, -1, -1));

        claimAmountLabel.setText("Claim Amount ($): *");
        claimDetailsPanel.add(claimAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 139, -1, -1));
        claimDetailsPanel.add(claimAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 136, 104, -1));

        notesLabel.setText("Additional Notes:");
        claimDetailsPanel.add(notesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        notesTextArea.setColumns(20);
        notesTextArea.setLineWrap(true);
        notesTextArea.setRows(5);
        notesTextArea.setWrapStyleWord(true);
        notesScrollPane.setViewportView(notesTextArea);

        claimDetailsPanel.add(notesScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 710, 65));

        add(claimDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 740, 270));

        documentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Supporting Documents:");
        documentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 9, -1, -1));

        uploadButton.setText("Upload Document");
        documentPanel.add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, -1, -1));

        add(documentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 740, 30));

        clearButton.setText("Clear");
        add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        submitButton.setText("Submit Claim");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel claimAmountLabel;
    private javax.swing.JTextField claimAmountTextField;
    private javax.swing.JPanel claimDetailsPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JTextField diagnosisTextField;
    private javax.swing.JPanel documentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JScrollPane notesScrollPane;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JTextField patientIdTextField;
    private javax.swing.JPanel patientInfoPanel;
    private javax.swing.JComboBox<String> policyComboBox;
    private javax.swing.JLabel policyLabel;
    private javax.swing.JLabel providerNameLabel;
    private javax.swing.JTextField providerNameTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField serviceDateChooser;
    private javax.swing.JLabel serviceDateLabel;
    private javax.swing.JComboBox<String> serviceTypeComboBox;
    private javax.swing.JLabel serviceTypeLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
