/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class SupplierInventoryManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierInventoryManagementPanel
     */
    public SupplierInventoryManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addStockButton = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox<>();
        sortLabel = new javax.swing.JLabel();
        sortComboBox = new javax.swing.JComboBox<>();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        updateStockButton = new javax.swing.JButton();
        generateReportButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        statsPanel = new javax.swing.JPanel();
        totalItemsLabel = new javax.swing.JLabel();
        lowStockLabel = new javax.swing.JLabel();
        outOfStockLabel = new javax.swing.JLabel();
        expiringLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Inventory Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel2.setText("Manage supplier warehouse inventory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        searchLabel.setText("Search:");
        add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, -1, -1));
        add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 63, 100, -1));

        searchButton.setText("Search");
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 63, -1, -1));

        addStockButton.setText("+ Add Stock");
        add(addStockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 63, -1, -1));

        filterLabel.setText("Filter:");
        add(filterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 95, -1, -1));

        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Items", "In Stock", "Low Stock", "Out of Stock", "Expiring Soon" }));
        add(filterComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 92, 100, -1));

        sortLabel.setText("Sort By:");
        add(sortLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 95, 72, -1));

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Stock", "Price", "Expiry" }));
        add(sortComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 92, 97, -1));

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Med ID", "Name", "Category", "Stock", "Reorder", "Price", "Exp Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryScrollPane.setViewportView(inventoryTable);

        add(inventoryScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 740, 270));

        updateStockButton.setText("Update Stock");
        add(updateStockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        generateReportButton.setText("Generate Report");
        add(generateReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        exportButton.setText("Export Data");
        add(exportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        totalItemsLabel.setText("Total Items: 125");

        lowStockLabel.setText("Low Stock: 8");

        outOfStockLabel.setText("Out of Stock: 5");

        expiringLabel.setText("Expiring Soon: 3");

        totalValueLabel.setText("Total Value: $245,800");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalItemsLabel)
                .addGap(34, 34, 34)
                .addComponent(lowStockLabel)
                .addGap(38, 38, 38)
                .addComponent(outOfStockLabel)
                .addGap(40, 40, 40)
                .addComponent(expiringLabel)
                .addGap(60, 60, 60)
                .addComponent(totalValueLabel)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalItemsLabel)
                    .addComponent(lowStockLabel)
                    .addComponent(outOfStockLabel)
                    .addComponent(expiringLabel)
                    .addComponent(totalValueLabel))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(statsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 740, 45));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStockButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel expiringLabel;
    private javax.swing.JButton exportButton;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lowStockLabel;
    private javax.swing.JLabel outOfStockLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> sortComboBox;
    private javax.swing.JLabel sortLabel;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel totalItemsLabel;
    private javax.swing.JLabel totalValueLabel;
    private javax.swing.JButton updateStockButton;
    // End of variables declaration//GEN-END:variables
}
