/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class SupplierDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierDashboardPanel
     */
    public SupplierDashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportsButton = new javax.swing.JButton();
        appointmentsSectionLabel = new javax.swing.JLabel();
        productsCard = new javax.swing.JPanel();
        productsCountLabel = new javax.swing.JLabel();
        productsTextLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        revenueCard = new javax.swing.JPanel();
        revenueCountLabel = new javax.swing.JLabel();
        revenueTextLabel = new javax.swing.JLabel();
        ordersScrollPane = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        ordersCard = new javax.swing.JPanel();
        ordersCountLabel = new javax.swing.JLabel();
        ordersTextLabel = new javax.swing.JLabel();
        quickActionsLabel = new javax.swing.JLabel();
        manageCatalogButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        viewOrdersButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        pharmaciesCard = new javax.swing.JPanel();
        pharmaciesTextLabel = new javax.swing.JLabel();
        pharmaciesCountLabel = new javax.swing.JLabel();
        inventoryButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportsButton.setText("Reports");
        add(reportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 170, 36));

        appointmentsSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        appointmentsSectionLabel.setText("RECENT PURCHASE ORDERS");
        add(appointmentsSectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 300, 20));

        productsCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        productsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productsCountLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        productsCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productsCountLabel.setText("125");
        productsCard.add(productsCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 145, 32));

        productsTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productsTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productsTextLabel.setText("Total Products");
        productsCard.add(productsTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        add(productsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 175, 95));

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("Refresh");
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 90, 26));

        revenueCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        revenueCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        revenueCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        revenueCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        revenueCountLabel.setText("$2.5M");
        revenueCard.add(revenueCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 145, 32));

        revenueTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        revenueTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        revenueTextLabel.setText("Monthly Revenue");
        revenueCard.add(revenueTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        add(revenueCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 175, 95));

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Pharmacy", "Items", "Amount", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersTable.setRowHeight(30);
        ordersScrollPane.setViewportView(ordersTable);

        add(ordersScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 745, 240));

        ordersCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ordersCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ordersCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ordersCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordersCountLabel.setText("18");
        ordersCard.add(ordersCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 145, 32));

        ordersTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordersTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordersTextLabel.setText("Pending Orders");
        ordersCard.add(ordersTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        add(ordersCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 175, 95));

        quickActionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        quickActionsLabel.setText("QUICK ACTIONS");
        add(quickActionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 20));

        manageCatalogButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageCatalogButton.setText("Manage Catalog");
        add(manageCatalogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 36));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("SUPPLIER DASHBOARD");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 28));

        viewOrdersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewOrdersButton.setText("View Orders");
        add(viewOrdersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, 36));

        descriptionLabel.setText("Manage medications and purchase orders");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 16));

        pharmaciesCard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pharmaciesCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pharmaciesTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pharmaciesTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pharmaciesTextLabel.setText("Active Pharmacies");
        pharmaciesCard.add(pharmaciesTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 145, 32));

        pharmaciesCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pharmaciesCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pharmaciesCountLabel.setText("45");
        pharmaciesCard.add(pharmaciesCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 145, 32));

        add(pharmaciesCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 175, 95));

        inventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryButton.setText("Inventory");
        add(inventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 170, 36));

        welcomeLabel.setText("Welcome, [Supplier Name]");
        add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 16));

        logoutButton.setText("Logout");
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentsSectionLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageCatalogButton;
    private javax.swing.JPanel ordersCard;
    private javax.swing.JLabel ordersCountLabel;
    private javax.swing.JScrollPane ordersScrollPane;
    private javax.swing.JTable ordersTable;
    private javax.swing.JLabel ordersTextLabel;
    private javax.swing.JPanel pharmaciesCard;
    private javax.swing.JLabel pharmaciesCountLabel;
    private javax.swing.JLabel pharmaciesTextLabel;
    private javax.swing.JPanel productsCard;
    private javax.swing.JLabel productsCountLabel;
    private javax.swing.JLabel productsTextLabel;
    private javax.swing.JLabel quickActionsLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JPanel revenueCard;
    private javax.swing.JLabel revenueCountLabel;
    private javax.swing.JLabel revenueTextLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewOrdersButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
