/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import business.SystemData;

/**
 *
 * @author Sandeep Patil
 */
public class SystemAdminDashboardPanel extends javax.swing.JPanel {
        private SystemData systemData = SystemData.getInstance();
    /**
     * Creates new form SystemAdminDashboardPanel
     */
    public SystemAdminDashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        navigationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageEnterprisesButton = new javax.swing.JButton();
        manageOrganizationsButton = new javax.swing.JButton();
        manageEmployeesButton = new javax.swing.JButton();
        viewReportsButton = new javax.swing.JButton();
        systemSettingsButton = new javax.swing.JButton();
        registerUserButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        workspacePanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Navigation Menu");

        manageEnterprisesButton.setText("Manage Enterprises");
        manageEnterprisesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterprisesButtonActionPerformed(evt);
            }
        });

        manageOrganizationsButton.setText("Manage Organizations");
        manageOrganizationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationsButtonActionPerformed(evt);
            }
        });

        manageEmployeesButton.setText("Manage Employees");
        manageEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesButtonActionPerformed(evt);
            }
        });

        viewReportsButton.setText("View Reports");
        viewReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsButtonActionPerformed(evt);
            }
        });

        systemSettingsButton.setText("System Settings");
        systemSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemSettingsButtonActionPerformed(evt);
            }
        });

        registerUserButton.setText("Register User");
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageOrganizationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageEmployeesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(systemSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageEnterprisesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(manageEnterprisesButton)
                .addGap(28, 28, 28)
                .addComponent(manageOrganizationsButton)
                .addGap(27, 27, 27)
                .addComponent(manageEmployeesButton)
                .addGap(26, 26, 26)
                .addComponent(viewReportsButton)
                .addGap(30, 30, 30)
                .addComponent(systemSettingsButton)
                .addGap(26, 26, 26)
                .addComponent(registerUserButton)
                .addGap(31, 31, 31)
                .addComponent(logoutButton)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(navigationPanel);

        workspacePanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(workspacePanel);

        jPanel1.add(jSplitPane2, "card2");

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void systemSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemSettingsButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this,
            "System Settings panel coming soon!",
            "Coming Soon",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_systemSettingsButtonActionPerformed

    private void manageEnterprisesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterprisesButtonActionPerformed
        // TODO add your handling code here:
         // Create ManageEnterprisesPanel
        ManageEnterprisesPanel manageEnterprisesPanel = new ManageEnterprisesPanel();
        
        // Remove all existing components from workspace
        workspacePanel.removeAll();
        
        // Add the panel to workspace
        workspacePanel.add(manageEnterprisesPanel, "manageEnterprises");
        
        // Show the panel
        java.awt.CardLayout layout = (java.awt.CardLayout) workspacePanel.getLayout();
        layout.show(workspacePanel, "manageEnterprises");
        
        // Refresh workspace
        workspacePanel.revalidate();
        workspacePanel.repaint();
    }//GEN-LAST:event_manageEnterprisesButtonActionPerformed

    private void manageOrganizationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationsButtonActionPerformed
        // TODO add your handling code here:
        // Create ManageOrganizationsPanel
        ManageOrganizationsPanel manageOrganizationsPanel = new ManageOrganizationsPanel();
        
        // Remove all existing components from workspace
        workspacePanel.removeAll();
        
        // Add the panel to workspace
        workspacePanel.add(manageOrganizationsPanel, "manageOrganizations");
        
        // Show the panel
        java.awt.CardLayout layout = (java.awt.CardLayout) workspacePanel.getLayout();
        layout.show(workspacePanel, "manageOrganizations");
        
        // Refresh workspace
        workspacePanel.revalidate();
        workspacePanel.repaint();
    }//GEN-LAST:event_manageOrganizationsButtonActionPerformed

    private void manageEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesButtonActionPerformed
        // TODO add your handling code here:
        // Create ManageEmployeesPanel
        ManageEmployeesPanel manageEmployeesPanel = new ManageEmployeesPanel();
        
        // Remove all existing components from workspace
        workspacePanel.removeAll();
        
        // Add the panel to workspace
        workspacePanel.add(manageEmployeesPanel, "manageEmployees");
        
        // Show the panel
        java.awt.CardLayout layout = (java.awt.CardLayout) workspacePanel.getLayout();
        layout.show(workspacePanel, "manageEmployees");
        
        // Refresh workspace
        workspacePanel.revalidate();
        workspacePanel.repaint();
    }//GEN-LAST:event_manageEmployeesButtonActionPerformed
        
   
    
    private void viewReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportsButtonActionPerformed
        // TODO add your handling code here:
         javax.swing.JOptionPane.showMessageDialog(this,
            "View Reports panel coming soon!",
            "Coming Soon",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_viewReportsButtonActionPerformed

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        // TODO add your handling code here:
        RegisterUserPanel registerUserPanel = new RegisterUserPanel();
        workspacePanel.removeAll();
        workspacePanel.add(registerUserPanel, "registerUser");
        java.awt.CardLayout layout = (java.awt.CardLayout) workspacePanel.getLayout();
        layout.show(workspacePanel, "registerUser");
        workspacePanel.revalidate();
        workspacePanel.repaint();
        
    }//GEN-LAST:event_registerUserButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        systemData.logout();
        
        java.awt.Container parent = this.getParent();
        while (parent != null && !(parent instanceof MainApplicationFrame)) {
            parent = parent.getParent();
        }
        
        if (parent instanceof MainApplicationFrame) {
            MainApplicationFrame mainFrame = (MainApplicationFrame) parent;
            LoginPanel loginPanel = new LoginPanel();
            mainFrame.addPanel(loginPanel, "loginPanel");
            mainFrame.showPanel("loginPanel");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageEmployeesButton;
    private javax.swing.JButton manageEnterprisesButton;
    private javax.swing.JButton manageOrganizationsButton;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JButton systemSettingsButton;
    private javax.swing.JButton viewReportsButton;
    private javax.swing.JPanel workspacePanel;
    // End of variables declaration//GEN-END:variables
}
