/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class VerifyInsuranceEligibilityPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerifyInsuranceEligibilityPanel
     */
    public VerifyInsuranceEligibilityPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        patientSearchPanel = new javax.swing.JPanel();
        patientIdLabel = new javax.swing.JLabel();
        patientIdTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        selectedPatientLabel = new javax.swing.JLabel();
        insuranceInfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        insuranceProviderValueLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        policyNumberValueLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        policyTypeValueLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        statusValueLabel = new javax.swing.JLabel();
        verifyButton = new javax.swing.JButton();
        coverageDetailsPanel = new javax.swing.JPanel();
        deductibleLabel = new javax.swing.JLabel();
        deductibleValueLabel = new javax.swing.JLabel();
        copayLabel = new javax.swing.JLabel();
        copayValueLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        coverageLimitValueLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        outOfPocketValueLabel = new javax.swing.JLabel();
        eligibilityStatusLabel = new javax.swing.JLabel();
        eligibilityStatusValueLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Verify Insurance Eligibility");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 6, -1, -1));

        jLabel2.setText("Verify patient insurance coverage and benefits");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, -1));

        patientSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Search"));
        patientSearchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientIdLabel.setText("Patient ID:");
        patientSearchPanel.add(patientIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, -1));

        patientIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdTextFieldActionPerformed(evt);
            }
        });
        patientSearchPanel.add(patientIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        searchButton.setText("Search");
        patientSearchPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        selectedPatientLabel.setText("Selected: Div Div (P-12345)");
        patientSearchPanel.add(selectedPatientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        add(patientSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 740, 100));

        insuranceInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Insurance Information"));
        insuranceInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Insurance Provider:");
        insuranceInfoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, -1, -1));

        insuranceProviderValueLabel.setText("BlueCross BlueShield");
        insuranceInfoPanel.add(insuranceProviderValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 24, -1, -1));

        jLabel4.setText("Policy Number:");
        insuranceInfoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 46, -1, -1));

        policyNumberValueLabel.setText("POL-2024-00123");
        insuranceInfoPanel.add(policyNumberValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 46, -1, -1));

        jLabel5.setText("Policy Type:");
        insuranceInfoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, -1, -1));

        policyTypeValueLabel.setText("Family PPO");
        insuranceInfoPanel.add(policyTypeValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 68, -1, -1));

        jLabel6.setText("Status:");
        insuranceInfoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        statusValueLabel.setText("Active");
        insuranceInfoPanel.add(statusValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 90, -1, -1));

        verifyButton.setText("Verify Coverage");
        insuranceInfoPanel.add(verifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 118, -1, -1));

        add(insuranceInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 740, 160));

        coverageDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Coverage Details"));
        coverageDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deductibleLabel.setText("Annual Deductible:");
        coverageDetailsPanel.add(deductibleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 24, -1, -1));

        deductibleValueLabel.setText("$2,000 (Remaining: $1,200)");
        coverageDetailsPanel.add(deductibleValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 24, -1, -1));

        copayLabel.setText("Office Visit Copay:");
        coverageDetailsPanel.add(copayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 46, -1, -1));

        copayValueLabel.setText("$30");
        coverageDetailsPanel.add(copayValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 46, -1, -1));

        jLabel7.setText("Annual Coverage Limit:");
        coverageDetailsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 68, -1, -1));

        coverageLimitValueLabel.setText("$500,000");
        coverageDetailsPanel.add(coverageLimitValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 68, -1, -1));

        jLabel9.setText("Out-of-Pocket Max:");
        coverageDetailsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 90, -1, -1));

        outOfPocketValueLabel.setText("$5,000 (Paid: $1,500)");
        coverageDetailsPanel.add(outOfPocketValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 90, -1, -1));

        eligibilityStatusLabel.setText("Eligibility Status:");
        coverageDetailsPanel.add(eligibilityStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 112, -1, -1));

        eligibilityStatusValueLabel.setText("✓ Eligible for Coverage");
        coverageDetailsPanel.add(eligibilityStatusValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 134, -1, -1));

        add(coverageDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 740, 190));

        clearButton.setText("Clear");
        add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        printButton.setText("Print Verification");
        add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void patientIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel copayLabel;
    private javax.swing.JLabel copayValueLabel;
    private javax.swing.JPanel coverageDetailsPanel;
    private javax.swing.JLabel coverageLimitValueLabel;
    private javax.swing.JLabel deductibleLabel;
    private javax.swing.JLabel deductibleValueLabel;
    private javax.swing.JLabel eligibilityStatusLabel;
    private javax.swing.JLabel eligibilityStatusValueLabel;
    private javax.swing.JPanel insuranceInfoPanel;
    private javax.swing.JLabel insuranceProviderValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel outOfPocketValueLabel;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JTextField patientIdTextField;
    private javax.swing.JPanel patientSearchPanel;
    private javax.swing.JLabel policyNumberValueLabel;
    private javax.swing.JLabel policyTypeValueLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel selectedPatientLabel;
    private javax.swing.JLabel statusValueLabel;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
