/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author dives
 */
public class ViewPurchaseOrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPurchaseOrdersPanel
     */
    public ViewPurchaseOrdersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        statusFilterComboBox = new javax.swing.JComboBox<>();
        dateFromLabel = new javax.swing.JLabel();
        dateFromField = new javax.swing.JLabel();
        dateToLabel = new javax.swing.JLabel();
        dateToField = new javax.swing.JLabel();
        ordersScrollPane = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        viewDetailsButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        summaryLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Purchase Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        backButton.setText("Back");
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 6, -1, -1));

        jLabel2.setText("View and manage incoming purchase orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        jLabel3.setText("Search:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, -1, -1));
        add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 63, 148, -1));

        searchButton.setText("Search");
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 57, -1, -1));

        refreshButton.setText("Refresh");
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel4.setText("Status:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 95, -1, -1));

        statusFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Orders", "Pending", "Processing", "Shipped", "Delivered", "Cancelled" }));
        add(statusFilterComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 92, 148, -1));

        dateFromLabel.setText("From:");
        add(dateFromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 126, -1, -1));

        dateFromField.setText("[MM/DD/YYYY]");
        add(dateFromField, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 126, -1, -1));

        dateToLabel.setText("To:");
        add(dateToLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 148, -1, -1));

        dateToField.setText("[MM/DD/YYYY]");
        add(dateToField, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 148, -1, -1));

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Pharmacy", "Items", "Amount", "Date", "Status", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersTable.setRowHeight(30);
        ordersScrollPane.setViewportView(ordersTable);

        add(ordersScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 740, 330));

        viewDetailsButton.setText("View Details");
        add(viewDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        processButton.setText("Process Order");
        add(processButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        exportButton.setText("Export List");
        add(exportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, -1));

        summaryLabel.setText("Total Orders: 48 | Pending: 12 | Processing: 8 | Shipped: 15 | Delivered: 13");
        add(summaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dateFromField;
    private javax.swing.JLabel dateFromLabel;
    private javax.swing.JLabel dateToField;
    private javax.swing.JLabel dateToLabel;
    private javax.swing.JButton exportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane ordersScrollPane;
    private javax.swing.JTable ordersTable;
    private javax.swing.JButton processButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> statusFilterComboBox;
    private javax.swing.JLabel summaryLabel;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables
}
